
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Pos_store_2_ibi_devis/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<style type="text/css">
  tr:hover td{
    background-color: #ccc !important;
  }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Devis<small></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Accueil</a></li>
      <li class="active">Devis</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                      
                      


                  <?php is_allowed('pos_store_2_ibi_devis_add', function(){ ?>
                  <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="voir les devis approuvées" href="<?=  site_url('administrator/pos_store_2_ibi_devis/index'); ?>"><i class="fa fa-list" ></i>&nbsp;&nbsp;Devis approuvées</a>

                     <?php }) ?>

                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"> Devis</h3>
                     <h5 class="widget-user-desc">Liste des commandes en attentes  <i class="label bg-yellow"><?= $pos_store_2_ibi_devis_counts; ?>  Elément<?php if($pos_store_2_ibi_devis_counts > 1)echo 's'; ?></i></h5>
                  </div>

                  <form name="form_pos_store_2_ibi_devis" id="form_pos_store_2_ibi_devis" action="<?= base_url('administrator/pos_store_2_ibi_devis/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr style="background-color: #ccc !important;">
                           
                           <th style="text-align: center !important">&#8470; &nbsp;du devis</th>
                           <th style="text-align: center !important">Description</th>
                           <th style="text-align: center !important">Client</th>
                            <th style="text-align: center !important">Par</th>
                           <th style="text-align: center !important">Date de création</th>
                          
                           <th style="text-align: center !important">Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_pos_store_2_ibi_devis">
                     <?php foreach($pos_store_2_ibi_deviss as $pos_store_2_ibi_devis): ?>
                        <tr>
                            <td style="text-align: center !important"><?= _ent($pos_store_2_ibi_devis->CODE_DEVIS); ?></td> 

                           <td style="text-align: center !important"><?= _ent($pos_store_2_ibi_devis->TITRE_DEVIS); ?></td> 
                          
                           <td style="text-align: center !important"><?= _ent($pos_store_2_ibi_devis->NOM_CLIENT); ?></td>

                          <td style="text-align: center !important"><?= _ent($pos_store_2_ibi_devis->full_name); ?></td> 

                         <td style="text-align: center !important"><?= _ent($pos_store_2_ibi_devis->DATE_CREATION_DEVIS); ?></td>
                             
                           <td style="text-align: center !important" width="200">


                              <?php is_allowed('pos_store_2_ibi_devis_view', function() use ($pos_store_2_ibi_devis){?>


                          <a class="btn btn-flat btn-primary btn_action  btn-xs" id="btn_cancel" title="Approuver un devis">
                            <i class="fa fa-check" ></i><input type="hidden" id="devis_id" value="<?php echo $pos_store_2_ibi_devis->ID_DEVIS; ?>" name="id_devis">
                            </a>

                                
                              <?php }) ?>
















                              <?php is_allowed('pos_store_2_ibi_devis_update', function() use ($pos_store_2_ibi_devis){?>
                              <a href="<?= site_url('administrator/pos_store_2_ibi_devis/edit/' . $pos_store_2_ibi_devis->ID_DEVIS); ?>" class="btn btn-info btn-xs"><i class="fa fa-edit "></i> </a>
                              <?php }) ?>
                              <?php is_allowed('pos_store_2_ibi_devis_delete', function() use ($pos_store_2_ibi_devis){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/pos_store_2_ibi_devis/delete/' . $pos_store_2_ibi_devis->ID_DEVIS); ?>" class="btn btn-danger btn-xs remove-data"><i class="fa fa-close"></i> </a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($pos_store_2_ibi_devis_counts == 0) :?>
                         <tr style="color:red; text-align: center;">
                           <td colspan="100">
                           Pas du contenu à afficher
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'TITRE_DEVIS' ? 'selected' :''; ?> value="TITRE_DEVIS">TITRE DEVIS</option>
                           <option <?= $this->input->get('f') == 'CODE_DEVIS' ? 'selected' :''; ?> value="CODE_DEVIS">CODE DEVIS</option>
                           <option <?= $this->input->get('f') == 'REF_CLIENT_DEVIS' ? 'selected' :''; ?> value="REF_CLIENT_DEVIS">REF CLIENT DEVIS</option>
                           <option <?= $this->input->get('f') == 'TYPE_DEVIS' ? 'selected' :''; ?> value="TYPE_DEVIS">TYPE DEVIS</option>
                           <option <?= $this->input->get('f') == 'DATE_CREATION_DEVIS' ? 'selected' :''; ?> value="DATE_CREATION_DEVIS">DATE CREATION DEVIS</option>
                           <option <?= $this->input->get('f') == 'DATE_MOD_DEVIS' ? 'selected' :''; ?> value="DATE_MOD_DEVIS">DATE MOD DEVIS</option>
                           <option <?= $this->input->get('f') == 'AUTHOR_DEVIS' ? 'selected' :''; ?> value="AUTHOR_DEVIS">AUTHOR DEVIS</option>
                           <option <?= $this->input->get('f') == 'COEFFICIENT_DEVIS' ? 'selected' :''; ?> value="COEFFICIENT_DEVIS">COEFFICIENT DEVIS</option>
                           <option <?= $this->input->get('f') == 'TOTAL_DEVIS' ? 'selected' :''; ?> value="TOTAL_DEVIS">TOTAL DEVIS</option>
                           <option <?= $this->input->get('f') == 'TOTAL_FINAL_DEVIS' ? 'selected' :''; ?> value="TOTAL_FINAL_DEVIS">TOTAL FINAL DEVIS</option>
                           <option <?= $this->input->get('f') == 'TYPE_DELAY_DEVIS' ? 'selected' :''; ?> value="TYPE_DELAY_DEVIS">TYPE DELAY DEVIS</option>
                           <option <?= $this->input->get('f') == 'TEMPS_DELAY_DEVIS' ? 'selected' :''; ?> value="TEMPS_DELAY_DEVIS">TEMPS DELAY DEVIS</option>
                           <option <?= $this->input->get('f') == 'COND_PAID_DEVIS' ? 'selected' :''; ?> value="COND_PAID_DEVIS">COND PAID DEVIS</option>
                           <option <?= $this->input->get('f') == 'PERCENT_PAID_DEVIS' ? 'selected' :''; ?> value="PERCENT_PAID_DEVIS">PERCENT PAID DEVIS</option>
                           <option <?= $this->input->get('f') == 'PERCENT_PAID_LIVR_DEVIS' ? 'selected' :''; ?> value="PERCENT_PAID_LIVR_DEVIS">PERCENT PAID LIVR DEVIS</option>
                           <option <?= $this->input->get('f') == 'VALID_OFFRE_DEVIS' ? 'selected' :''; ?> value="VALID_OFFRE_DEVIS">VALID OFFRE DEVIS</option>
                           <option <?= $this->input->get('f') == 'STATUT_DEVIS' ? 'selected' :''; ?> value="STATUT_DEVIS">STATUT DEVIS</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/pos_store_2_ibi_devis');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   



   
       $('#btn_cancel').click(function(){
        var id_devis=$('#devis_id').val();
      //alert(id_devis);
        swal({
            title: "Êtes-vous sûr de vouloir Approuver",
            text: "Le devis deviendra une fiche de travail",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes!",
            cancelButtonText: "No!",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
          window.location.href = BASE_URL + 'administrator/pos_store_2_ibi_devis/approuver_commande/'+id_devis;
            }
          });
    
        return false;
      }); /*end btn approuver*/




    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_pos_store_2_ibi_devis').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/pos_store_2_ibi_devis/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>