
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Pos Store 2 Categorie      <small><?= cclang('detail', ['Pos Store 2 Categorie']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/pos_store_2_categorie'); ?>">Pos Store 2 Categorie</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Pos Store 2 Categorie</h3>
                     <h5 class="widget-user-desc">Detail Pos Store 2 Categorie</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_pos_store_2_categorie" id="form_pos_store_2_categorie" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Categorie Id </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_categorie->categorie_id); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Désignation </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_categorie->categorie_designation); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Categorie User Id </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_categorie->full_name); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Type </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_categorie->categorie_type); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Date De La Création </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_categorie->categorie_date_creation); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Date De La Modification </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_categorie->categorie_date_modification); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('pos_store_2_categorie_update', function() use ($pos_store_2_categorie){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit pos_store_2_categorie (Ctrl+e)" href="<?= site_url('administrator/pos_store_2_categorie/edit/'.$pos_store_2_categorie->categorie_id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Pos Store 2 Categorie']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/pos_store_2_categorie/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Pos Store 2 Categorie']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
