<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/devis/adds/<?php $this->uri->segment(4) ?>';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {

       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<style type="text/css">
  tr:hover td{
    background-color: #ccc !important;
  }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Devis Historique<small></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Accueil</a></li>
      <li class="active">Devis</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <form name="form_devis" id="form_fiche_travail">
                        <div class="widget-user-header ">
                         <div class="row pull-center" style="margin-left:5%">
                          <div  class="col-md-8">
                             <div class="col-sm-6 padd-left-0 " >
                                <select type="text" class="form-control chosen chosen-select" name="f" id="client_select" >
                                   <option value="">Choisis le client</option>
                                   <?php 
                                    foreach($query_clients->result() as $query_cl) {
                                      $id_cl = $query_cl->ID_CLIENT;
                                      echo '<option value='.$id_cl.'>'.$query_cl->NOM_CLIENT.'</option>';
                                    }
                                   ?>
                                </select>
                             </div>
                          </div>
                        </div>
                      </div>
                  </form>

                  <div class="table-responsive"> 
                    <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr>
                           <th>&#8470; &nbsp;</th>
                           <th>&#8470; &nbsp;du devis</th>
                           <th>Description</th>
                           <th>Client</th>
                           <th width="150">Total</th>
                           <th>Date de création</th>
                           <th>Status</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_devis">
                     <?php $i = 0;
                     foreach($deviss as $devis): 
                      $i++;
                      ?>
                        <tr>
                          <td><?= $i?></td>
                          <td><?= _ent($devis->CODE_DEVIS); ?></td> 
                          <td><?= _ent($devis->TITRE_DEVIS); ?></td>
                          <td><?php $id_client = _ent($devis->REF_CLIENT_DEVIS);
                          $client = $this->db->get_where('pos_ibi_clients', array('ID_CLIENT'=> $id_client))->row();
                          $client_name = isset($client->NOM_CLIENT) ? $client->NOM_CLIENT : '';
                          echo $client_name;
                           ?></td>
                           <td><?= number_format(round(_ent($devis->TOTAL_FINAL_DEVIS)), 0, ',', ' ') ?></td>
                          <td><?= _ent($devis->DATE_CREATION_DEVIS); ?></td>
                          <td>
                          <?php 
                           if($devis->STATUT_DEVIS==1){
                             echo '<i style="background-color:green" class="label">Approuvé</i>';
                           }else{
                            echo '<i class="label bg-yellow">En attente</i>';
                           }
                         ?>
                         </td>  
                         <!--<td width="50">
                          <?php //is_allowed('devis_view', function() use ($devis){?>  
                            <center>
                            <a title="voir détail du devis" id_devis ='<?= $devis->ID_DEVIS ?>' id="voir_detail" class="btn btn-warning btn-xs"><i class="fa fa-eye "></i> </a></center>              
                            <?php //}) ?>
                           </td> -->
                        </tr>



                <!-- Modal -->
                <div id="modal_detail" class="modal fade" role="dialog">
                  <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title"></h4>
                      </div>  
                      <div class="modal-body"> 
                        
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>
                      </div>
                    </div>
                  </div>
                </div>




                      <?php endforeach; ?>


                      <?php if ($devis_counts == 0) :?>
                         <tr style="color:red; text-align: center;">
                           <td colspan="100">
                           Pas de contenu à afficher
                           </td>
                         </tr>
                      <?php endif; ?>

                      </tbody>
                    </table>
                  </div>
               </div>
               <hr>
               <div class="row">
                  <div class="col-md-8">
                  </div>                
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?php //$pagination; ?>
                     </div>
                  </div>
               </div>

           

           <?= form_open('', [
                          'name'    => 'add_devis_form', 
                          'class'   => 'add_devis_form', 
                          'id'      => 'add_devis_form', 
                          'enctype' => 'multipart/form-data', 
                          'method'  => 'POST'
                                      ]); ?>
           <input type="hidden" value="" name="ids_devis" id="ids_devis">                         
           <input type="hidden" value="" name="titre" id="titre">
           <input type="hidden" value="" name="qte" id="qte">
           <input type="hidden" value="" name="remise_val" id="remise_val">
           <input type="hidden" value="" name="selected_rems" id="selected_rems">
           <input type="hidden" value="<?=$this->uri->segment(4)?>" name="store">
          <?= form_close(); ?>


                     
               </div>
            </div>
            <!--/box body -->
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){

    $('#client_select').change(function() {
      var client_sel = $('#client_select').val();
      $.ajax({
        url: BASE_URL + '/administrator/devis/historique_filtre/<?=$this->uri->segment(4)?>',
        data: {client_sel: client_sel},
        dataType: 'json',
        type: 'post',
        success: function(data) {
          $('#tbody_devis').html(data.tableau)
        }
      })
    })
    $(document).on('click', '#voir_detail', function() {
      var id_devis = $(this).attr('id_devis');
      $.ajax({
        url: BASE_URL + '/administrator/devis/historique_view/<?=$this->uri->segment(4)?>/' + id_devis,
        type: 'post',
        dataType: 'json',
        success: function(data) {
          $('#modal_detail').modal('show')
          $('.modal-body').html('');
          $('.modal-body').append(`<table class="table table-bordered table-striped dataTable"><thead><tr><th>Codebar</th><th>Produit</th><th>Prix</th><th>Quantité</th>
                             <th>Q. Ajoutée</th><th>Total</th><th>Unité</th></tr></thead><tbody id="show_view"></tbody></table>`);
          // for(var i = 0; i < data.devis.length; i++) {
          //   $('#code_bar').val(data.devis.REF_PRODUCT_CODEBAR_DEVIS_PROD);
          //   $('#name_dev').val(data.devis.NAME_DEVIS_PROD)
          //   $('#prix_dev').val(data.devis.PRIX_DEVIS_PROD)
          //   $('#quantity_dev').val(data.devis.QUANTITE_DEVIS_PROD)
          //   $('#quantity_add_dev').val(data.devis.QUANTITE_ADD_DEVIS_PROD)
          // }
          var total_all = 0;
          var coefficient = 0;
          var total_final = 0;
          for(var i = 0; i < data.devis.length; i++) {
          coefficient = data.devis[i].COEFFICIENT_DEVIS;
          total_final = data.devis[i].TOTAL_FINAL_DEVIS;
            var quantit = data.devis[i].QUANTITE_DEVIS_PROD + data.devis[i].QUANTITE_ADD_DEVIS_PROD;
            var total = data.devis[i].PRIX_DEVIS_PROD * quantit; 
            total_all += total
            // console.log(data.devis[i])
            $('#show_view').append(`<tr><td>${data.devis[i].REF_PRODUCT_CODEBAR_DEVIS_PROD}</td><td>${data.devis[i].NAME_DEVIS_PROD}</td><td>${data.devis[i].PRIX_DEVIS_PROD}</td>
              <td>${data.devis[i].QUANTITE_DEVIS_PROD}</td><td>${data.devis[i].QUANTITE_ADD_DEVIS_PROD}</td><td>${total}</td><td>${data.devis[i].UNIT_DEVIS_PROD}</td></tr>`);
          }
          $('#show_view').append(`<tr><th colspan="5">COUT DE PRODUCTION</th><td class="text-center" colspan=""><input type="hidden" class="prixTotal" name="prixTotal" value="${total_all}">
                              ${total_all}
                            </td></tr>
                            <tr>
                            <th colspan="5">COEFFICIENT</th>  
                            <td class="text-center" colspan="">
                              <a class="btn btn-default btn-sm" data-toggle="modal" data-target="#coefficient">
                              ${coefficient}
                              </a>
                            </td>
                          </tr>
                          <tr>
                            <th colspan="5">TOTAL</th>
                            <td class="text-center" colspan="">
                              ${total_all * coefficient}
                            </td>
                          </tr>
                          <tr>
                            <th colspan="5">PRIX FINAL</th>
                            <td class="text-center" colspan="">
                              <a class="btn btn-default btn-sm" data-toggle="modal" data-target="#total_final">
                              ${total_final}
                              </a>
                           </td>
                          </tr>`);
        }
      })
    })
   });

</script>