
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/bon_sortie/add/<?=$this->uri->segment(4);?>';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });
   
   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Bon de sortie<small></small>
   </h1>
   <h5 class="widget-user-desc"><i class="label bg-yellow"><?= $bon_sortie_counts; ?>  <?= cclang('items'); ?></i></h5>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Accueil</a></li>
      <li class="active">Bon de sortie</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <form name="form_articles" id="form_articles" action="<?= base_url('administrator/bon_sortie/index/'.$this->uri->segment(4).''); ?>">
                  <div class="widget-user-header ">
                     <div class="row pull-center" style="margin-left:5%">
                        <div class="col-md-8">
                           <div class="col-sm-4 padd-left-0  " >
                              <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                           </div>
                           <div class="col-sm-2 padd-left-0 " >
                              <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                                 <option value=""><?= cclang('all'); ?></option>
                                  <option <?= $this->input->get('f') == 'NUMERO_BON' ? 'selected' :''; ?> value="NUMERO_BON">&#8470; &nbsp; du bon de sortie</option>
                                 <option <?= $this->input->get('f') == 'REF_FICHE_CODE' ? 'selected' :''; ?> value="REF_FICHE_CODE">&#8470; &nbsp; fiche</option>
                                 <option <?= $this->input->get('f') == 'DESCRIPTION' ? 'selected' :''; ?> value="DESCRIPTION">Description</option>
                                </select>
                           </div>
                           <div class="col-sm-1 padd-left-0 ">
                              <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                             <i class="fa fa-search"></i>
                              </button>
                           </div>
                           <div class="col-sm-1 padd-left-0 ">
                              <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/bon_sortie/index/'.$this->uri->segment(4).'');?>" title="<?= cclang('reset_filter'); ?>">
                              <i class="fa fa-undo"></i>
                              </a>
                           </div>
                       </div>
                        <?php is_allowed('bon_sortie_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="Ajouter le produit" href="<?=  site_url('administrator/bon_sortie/add/'.$this->uri->segment(4).''); ?>"><i class="glyphicon glyphicon-plus" ></i> </a>
                        <?php }) ?>
                        <?php is_allowed('bon_sortie_export', function(){?>
                        <a class="btn btn-flat btn-success" title="Export XLS" href="<?= site_url('administrator/bon_sortie/export/'.$this->uri->segment(4).''); ?>"><i class="fa fa-file-excel-o" ></i> </a>
                        <?php }) ?>
                     </div>
                  </div>
              </form>


                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>&#8470; &nbsp;du bon de sortie</th>
                           <th>&#8470; &nbsp;du fiche</th>
                           <th>Description</th>
                           <th>Demandeur</th>
                           <th>Statut</th>
                           <th>Date de création</th>
                           <th>Par</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_bon_sortie">
                     <?php foreach($bon_sortie as $bon_sorties): ?>
                        <tr>                           
                           <td><?= _ent($bon_sorties->NUMERO_BON); ?></td> 
                           <td><?= _ent($bon_sorties->REF_FICHE_CODE); ?></td> 
                           <td><?= _ent($bon_sorties->DESCRIPTION); ?></td> 
                           <td><?= _ent($bon_sorties->DEMANDEUR); ?></td>
                           <td>
                             <?php 
                               if($bon_sorties->STATUT_BON==2){
                                  echo '<i class="label bg-red">Annuler</i>';
                               }
                             ?>
                           </td>
                           <td><?= _ent($bon_sorties->DATE_CREATION); ?></td> 
                           <td><?php
                            $req=$this->db->query('select full_name from aauth_users where id='.$bon_sorties->AUTHOR);
                             foreach ($req->result() as $row){
                                    echo $row->full_name;
                              }
                            ?>
                           </td> 
                           <td width="150">
                            <?php if($bon_sorties->STATUT_BON == 2 ) { ?>
                            <?php is_allowed('bon_sortie_delete', function() use ($bon_sorties){?>
                              <a title="Supprimer ce bon de sortie" href="javascript:void(0);" data-href="<?= site_url('administrator/bon_sortie/delete/'.$this->uri->segment(4) .'/'. $bon_sorties->ID); ?>" class="btn btn-danger btn-xs remove-data"><i class="fa fa-close"></i></a>
                              <?php }) ?>
                              <?php }else{ ?>
                              <?php is_allowed('bon_sortie_delete_cancel', function() use ($bon_sorties){?>
                              <a title="Annuler bon de sortie" href="javascript:void(0);" data-href="<?= site_url('administrator/bon_sortie/to_cancel/'.$this->uri->segment(4).'/' . $bon_sorties->ID); ?>" class="btn btn-danger btn-xs remove-data"><i class="fa fa-close"></i></a>
                              <?php }) ?>
                              <?php } ?>
                              <?php is_allowed('bon_sortie_view', function() use ($bon_sorties){?>
                              <a href="<?= site_url('administrator/bon_sortie/view/'.$this->uri->segment(4).'/' . $bon_sorties->ID); ?>" class="btn btn-warning btn-xs"><span  class="glyphicon glyphicon-eye-open"></span></a>
                              <?php }) ?>
                               <?php is_allowed('bon_sortie_update', function() use ($bon_sorties){?>
                              <a href="<?= site_url('administrator/bon_sortie/retour/'.$this->uri->segment(4).'/'.$bon_sorties->ID); ?>" class="label-default"><span class="btn btn-default btn-xs">Retour</span></a>
                              <?php }) ?>
                              
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($bon_sortie_counts == 0) :?>
                         <tr style="color:red; text-align: center;">
                           <td colspan="100">
                           Pas du contenu à afficher
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <div class="row">
                  <div class="col-md-8">
                  </div>                
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
               
               <!-- /.widget-user -->
             
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Etes-vous sûr",
          text: "les données à supprimer ne peuvent pas être restaurées",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "oui supprimez-le",
          cancelButtonText: "non annuler plx",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_bon_sortie').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "Etes-vous sûr",
            text: "les données à supprimer ne peuvent pas être restaurées",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "oui supprimez-le",
            cancelButtonText: "non annuler plx",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/bon_sortie/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>