
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   // $('*').bind('keydown', 'Ctrl+a', function assets() {
   //     window.location.href = BASE_URL + '/administrator/devis/add/index/<?=$this->uri->segment(4);?>';
   //     return false;
   // });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<style type="text/css">
  tr:hover td{
    background-color: #ccc !important;
  }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Fiche de travail<small></small>
   </h1>
   <h5 class="widget-user-desc"><i class="label bg-yellow"><?= $fiche_charge_counts; ?> &nbsp; élément<?php if($fiche_charge_counts > 1)echo 's'; ?></i></h5>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Accueil</a></li>
      <li class="active">Fiche de travail</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <form name="form_fiche_travail" id="form_fiche_travail" action="<?= base_url('administrator/fiche_charge/index/'.$this->uri->segment(4)); ?>">
                    <div class="widget-user-header ">
                     <div class="row pull-center" style="margin-left:5%">
                      <div  class="col-md-8">
                         <div class="col-sm-4 padd-left-0  " >
                            <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                         </div>
                         <div class="col-sm-3 padd-left-0 " >
                            <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                               <option value=""><?= cclang('all'); ?></option>
                                <option <?= $this->input->get('f') == 'DESCRIPTION_FICHE_TRAV_CHAR' ? 'selected' :''; ?> value="DESCRIPTION_FICHE_TRAV_CHAR">Description</option>
                               <option <?= $this->input->get('f') == 'REF_PRISE_CHARGE' ? 'selected' :''; ?> value="REF_PRISE_CHARGE">Fiche de Prise en charge</option>
                               <option <?= $this->input->get('f') == 'NUMSERIE_FICHE_TRAV_CHAR' ? 'selected' :''; ?> value="NUMSERIE_FICHE_TRAV_CHAR">Numero fiche</option>
                               <option <?= $this->input->get('f') == 'CREATED_AT_FICHE_TRAV_CHAR' ? 'selected' :''; ?> value="CREATED_AT_FICHE_TRAV_CHAR">  Date de création</option>
                              </select>
                         </div>
                         <div class="col-sm-1 padd-left-0 ">
                            <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="Rechercher">
                            <i class="fa fa-search"></i>
                            </button>
                         </div>
                         <div class="col-sm-1 padd-left-0 ">
                            <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/fiche_charge/index/'.$this->uri->segment(4));?>" title="<?= cclang('reset_filter'); ?>">
                            <i class="fa fa-undo"></i>
                            </a>
                         </div>
                      </div>
                        <?php is_allowed('fiche_charge_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="aller à l'ajout du fiche de travail"><i class="fa fa-plus" ></i></a>
                        <?php }) ?>
                        <?php is_allowed('fiche_charge_export', function(){?>
                        <!-- <a class="btn btn-flat btn-success" title="Export XLSX" href="<?php //site_url('administrator/fiche_travail/export/'.$this->uri->segment(4).''); ?>"><i class="fa fa-file-excel-o" ></i></a> -->
                        <?php }) ?>
                    </div>
                  </div>
              </form>

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr>
                           <th>&#8470; &nbsp;du fiche</th>
                           <th>&#8470; &nbsp;de la fiche prise en charge</th>
                           <th>Description</th>
                           <th width="100">Client</th>   
                           <th>Par</th>
                           <th>status</th>
                           <th>Date de création</th>
                           <th>Date approbation</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_fiche_travail">
                     <?php 
                     $id_fiche ='';
                     foreach($fiche_charges as $fiche_travail): ?>

                     <?php $id_fiche = $fiche_travail->ID_FICHE_TRAV_CHAR ; ?>

                        <tr>
                           <td><?= _ent($fiche_travail->NUMSERIE_FICHE_TRAV_CHAR); ?></td>
                           <td><?= _ent($fiche_travail->REF_PRISE_CHARGE); ?></td>
                           <td><?= _ent($fiche_travail->DESCRIPTION_FICHE_TRAV_CHAR); ?> </td>  
                           <td><?= _ent($fiche_travail->NOM_CLIENT); ?></td>
                           <td><?= _ent($fiche_travail->full_name); ?></td>
                           <td>
                                 <?php  
                                   if($fiche_travail->STATUT_FICH_TRAV_CHAR == 1){
                                     echo '<i style="background-color:green" class="label">clôturé</i>';
                                   }elseif($fiche_travail->STATUT_FICH_TRAV_CHAR == 2){
                                     echo '<i class="label bg-red">Annuler</i>';
                                   }else{
                                     echo '<i class="label bg-yellow">En attente</i>';
                                   } 
                                   ?>
                           </td>
                           <td><?= _ent($fiche_travail->CREATED_AT_FICHE_TRAV_CHAR); ?></td> 
                           <td><?= _ent($fiche_travail->DATE_APPROBAT_FICH_TRAV_CHAR); ?></td>
                           <td width="150">  
                              <?php is_allowed('fiche_travail_view', function() use ($fiche_travail){?>
                              <a title="voir le détail du fiche" href="<?= site_url('administrator/fiche_charge/fiche_printable/'.$this->uri->segment(4).'/'. $fiche_travail->ID_FICHE_TRAV_CHAR); ?>" class="btn btn-primary btn-xs"><i class="fa fa-print"></i> </a>
                              <?php }) ?>
                              
                              <?php is_allowed('fiche_travail_approuved', function() use ($fiche_travail){
                               ?>
                               <?php if($fiche_travail->STATUT_FICH_TRAV_CHAR == 0){?>
                                <a title="Approuver la fiche" href="javascript:void(0);" data-href="<?= site_url('administrator/fiche_charge/approuved/' .$this->uri->segment(4).'/'. $fiche_travail->ID_FICHE_TRAV_CHAR); ?>" class="btn btn-warning btn-xs approuved-data"><i class="fa fa-lock"></i></a>
                                <a title="Modification de la fiche" href="<?= site_url('administrator/fiche_charge/edit/' .$this->uri->segment(4).'/'. $fiche_travail->ID_FICHE_TRAV_CHAR); ?>" class="btn btn-info btn-xs"><i class="fa fa-edit"></i></a>
                               <?php }elseif($fiche_travail->STATUT_FICH_TRAV_CHAR == 1){ ?>
                                <a title="Décloturer la fiche" href="javascript:void(0);" data-href="<?= site_url('administrator/fiche_charge/desapprouved/'.$this->uri->segment(4).'/'.$fiche_travail->ID_FICHE_TRAV_CHAR); ?>" class="btn btn-warning btn-xs desapprouved"><i class="fa fa-undo"></i></a>
                               <?php } ?>
                            <?php }) ?>
                              
                            <?php if($fiche_travail->STATUT_FICH_TRAV_CHAR == 2 ) { ?>
                              <?php is_allowed('fiche_travail_delete', function() use ($fiche_travail){?>
                              <a title="Supprimer cette fiche" href="javascript:void(0);" data-href="<?= site_url('administrator/fiche_charge/delete/' .$this->uri->segment(4).'/'. $fiche_travail->ID_FICHE_TRAV_CHAR); ?>" class="btn btn-danger btn-xs remove-data"><i class="fa fa-close"></i></a>
                               <?php }) ?>
                              <?php }else{ ?>
                                <?php is_allowed('fiche_travail_update', function() use ($fiche_travail){?>
                                  <!-- <a title="Editer cette fiche" href="<?php //site_url('administrator/fiche_charge/edit/'.$this->uri->segment(4).'/' . $fiche_travail->ID_FICHE_TRAV_CHAR.'/'.$fiche_travail->TYPE_DEVIS_FICHE); ?>" class="btn btn-info btn-xs"><i class="fa fa-edit "></i> </a> -->
                                <?php }) ?>
                                <?php is_allowed('fiche_travail_delete_cancel', function() use ($fiche_travail){?>
                                  <a title="Annuler cette fiche" href="javascript:void(0);" data-href="<?= site_url('administrator/fiche_charge/to_cancel/'.$this->uri->segment(4).'/' . $fiche_travail->ID_FICHE_TRAV_CHAR); ?>" class="btn btn-danger btn-xs remove-data"><i class="fa fa-close"></i></a>
                              <?php }) ?>
                              <?php } ?>
                           </td>
                        </tr>

                <!-- -class modal -->
                <!-- Modal update ticket -->
                <div class="modal fade" id="modal_add_fiche" tabindex="-1" role="dialog" aria-labelledby="modal_add_fiche">
                  <div class="modal-dialog" id="" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 id="modify_name">Ajout de la fiche de prise en charge</h4>
                      </div>

                      <div class="modal-body">
                        <div>
                            <a title="Ajouter une fiche de prise en charge" href="<?= site_url('administrator/power/add/'.$this->uri->segment(4)); ?>" class="btn btn-primary"><i class="fa fa-plus"> POWER</i></a>
                            <a title="Ajouter une fiche de prise en charge" href="<?= site_url('administrator/cool/add/'.$this->uri->segment(4)); ?>" class="btn btn-primary"><i class="fa fa-plus"> COOL</i></a>
                            <a title="Ajouter une fiche de prise en charge" href="<?= site_url('administrator/clean/add/'.$this->uri->segment(4)); ?>" class="btn btn-primary"><i class="fa fa-plus"> CLEAN</i></a>
                            <a title="Ajouter une fiche de prise en charge" href="<?= site_url('administrator/garage/add/'.$this->uri->segment(4)); ?>" class="btn btn-primary"><i class="fa fa-plus"> GARAGE</i></a>
                            <a title="Ajouter une fiche de prise en charge" href="<?= site_url('administrator/securite_incendie/add/'.$this->uri->segment(4)); ?>"  class="btn btn-primary"><i class="fa fa-plus"> SECURITE INCENDIE</i></a>
                        </div>
                      </div>
                      <div class="modal-footer" id="">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Annuler</button>
                        <!-- <button type="button" class="btn btn-primary"  id="btn_edit_paid_leave" style="background-color: #00c0ef;">Enregistrer</button> -->
                      </div>
                    </div>
                  </div>
                </div>

                      <?php endforeach; ?>

                      <?php if ($fiche_charge_counts == 0) :?>
                         <tr style="color:red; text-align: center;">
                           <td colspan="100">
                             Pas du contenu à afficher
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                  </div>                
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
       
              </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
   function avoid_multi_click_btn(btn_id, period) {
    $('.' + btn_id).attr('disabled', true);

    var my_interval = setInterval(function() {

      $('.' + btn_id).attr('disabled', false);

      clearInterval(my_interval);

    }, period);
  }

  $(document).ready(function(){

    $('.BOUTIQUE').change(function(){
        var boutique_id = $(this).val();
       
        $.ajax({
                url: BASE_URL + '/administrator/fiche_travail/select_famille/<?=$this->uri->segment(4);?>',
                type: 'POST',
                async:false,
                dataType: 'json',
                data: {boutique_id:boutique_id},
                success:function(data)
                {  
                $('.FAMILLE').html(data);
                $('.store').val(boutique_id);              
                }
            });
       });
      $('.FAMILLE').change(function(){
        window.storeuri = $('.BOUTIQUE').val();
        var store = $('.store').val();
        var famille = $(this).val();
    
        $.ajax({
                url: BASE_URL + '/administrator/fiche_travail/select_categorie/'+store,
                type: 'POST',
                async:false,
                dataType: 'json',
                data: {famille:famille},                                                         
                success:function(data)
                {  
                $('.CATEGORIE').html(data);               
                }
            });
       });


    $('.btn_verified').click(function(){

        var id_fiche = $(this).find('input[name=btnsend]').val();
        var boutique = $("#boutique_transfer"+id_fiche).children("option:selected").val();
        var famille = $("#famille_transfer"+id_fiche).children("option:selected").val();
        var categorie = $("#fiche_categorie"+id_fiche).children("option:selected").val();
        var cout = $('#cout'+id_fiche).val();
        var quantite = $('#quantite'+id_fiche).val();
        var prix = $('#prix'+id_fiche).val();
        var description = $('#description'+id_fiche).val();
        
        if(boutique == ''){
          sweetAlert('Donner une boutique');
           return false;
        }else if(famille == ''){
          sweetAlert('Donner une famille');
           return false;
        }else if(quantite == ''){
          sweetAlert('Donner une quantité');
           return false;
        }else if(prix == ''){
          sweetAlert('Donner un prix');
           return false;
        }else if(description == ''){
          sweetAlert('Donner le nom');
           return false;
        }else{

        avoid_multi_click_btn('btn_save', 25000);

        var save_type = $(this).attr('data-stype');
        
        $('.loading').show();
        $.ajax({
            url: BASE_URL + '/administrator/fiche_travail/produit_transfert/<?=$this->uri->segment(4)?>/'+id_fiche,
            type: 'POST',
            dataType: 'json',
            data: {
              id_fiche:id_fiche,
              boutique:boutique,
              famille:famille,
              categorie:categorie,
              cout:cout,
              quantite:quantite,
              prix:prix,
              description:description},
          })

          .done(function(res) {

            if (res.success) {
              if (save_type == 'back') {
                window.location.href = res.redirect;
                return;
              }

              $('.message').printMessage({
                message: res.message
              });
              $('.message').fadeIn();
              resetForm();
              $('.chosen option').prop('selected', false).trigger('chosen:updated');

            } else {

              $('.message').printMessage({
                message: res.message,
                type: 'warning'
              });
            }
          })

          .fail(function() {
            $('.message').printMessage({
              message: 'Error save data',
              type: 'warning'
            });

          })
          .always(function() {

            $('.loading').hide();
            $('html, body').animate({
              scrollTop: $(document).height()
            }, 2000);

          });

        }
      return false;
    });

    $('.btn_add_new').click(function() {
        $('#modal_add_fiche').modal('show');
    })
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Etes-vous sûr",
          text: "les données à supprimer ne peuvent pas être restaurées",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "oui supprimez-le",
          cancelButtonText: "non annuler plx",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });
    $('.approuved-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Etes vous sur de vouloir",
          text: "Approuver cette fiche de travail",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "oui approuvez-le",
          cancelButtonText: "no annuler plx",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });

    $('.desapprouved').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Êtes-vous sûr",
          text: "La fiche de travail correspondante sera décloturer",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "oui desapprouvez-le",
          cancelButtonText: "no annuler plx",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });

    $('.recancel-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Etes-vous sûr",
          text: "les données annuler seront restaurées",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "oui restaurez-le",
          cancelButtonText: "no annuler plx",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });

  }); /*end doc ready*/
</script>