
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Pos_store_2_ibi_commande/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>


<style type="text/css">
  tr:hover td{
    background-color: #ccc !important;
  }
</style>


<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Pos Store 2 Ibi Commande<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Pos Store 2 Ibi Commande</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('pos_store_2_ibi_commande_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="voir les commandes approuvés" href="<?=  site_url('administrator/pos_store_2_ibi_commande'); ?>"><i class="fa fa-undo" ></i>&nbsp; Retourner</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Pos Store 2 Ibi Commande</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Pos Store 2 Ibi Commande']); ?>  <i class="label bg-yellow"><?= $pos_store_2_ibi_commande_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_pos_store_2_ibi_commande" id="form_pos_store_2_ibi_commande" action="<?= base_url('administrator/pos_store_2_ibi_commande/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr style="background-color:#ccc  !important;">
                           
                           <th style="text-align: center !important;">&#8470; &nbsp;de la commande</th>
                           <th style="text-align: center !important;">Description</th>
                           <th style="text-align: center !important;">Client</th>
                           <th style="text-align: center !important;">Utilisateur</th>
                           <th style="text-align: center !important;">Date de la création</th>
                           <th style="text-align: center !important;">Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_pos_store_2_ibi_commande">
                     <?php foreach($pos_store_2_ibi_commandes as $pos_store_2_ibi_commande): ?>
                        <tr>
                           
                           <td style="text-align: center !important;"><?= _ent($pos_store_2_ibi_commande->commande_numero); ?></td> 
                           <td style="text-align: center !important;"><?= _ent($pos_store_2_ibi_commande->commande_article_decription); ?></td>
                           <td style="text-align: center !important;"><?= _ent($pos_store_2_ibi_commande->NOM_CLIENT); ?></td>
                             
                           <td style="text-align: center !important;"><?= _ent($pos_store_2_ibi_commande->full_name); ?></td>
                             
                           <td style="text-align: center !important;"><?= _ent($pos_store_2_ibi_commande->commande_date); ?></td> 

                              
                           <td style="text-align: center !important;" width="100">
                              <?php is_allowed('pos_store_2_ibi_commande_view', function() use ($pos_store_2_ibi_commande){?>
                              <a href="<?= site_url('administrator/pos_store_2_ibi_commande/view/' . $pos_store_2_ibi_commande->commande_id); ?>" class="btn btn-warning btn-xs"><i class="fa fa-eye-slash"></i></a>
                              <?php }) ?>
                              <?php is_allowed('pos_store_2_ibi_commande_update', function() use ($pos_store_2_ibi_commande){?>
                              <a style="margin-left: 4px" href="<?= site_url('administrator/pos_store_2_ibi_commande/edit/' . $pos_store_2_ibi_commande->commande_id); ?>" class="btn btn-info btn-xs"><i class="fa fa-edit "></i> </a>
                              <?php }) ?>
                              <?php is_allowed('pos_store_2_ibi_commande_delete', function() use ($pos_store_2_ibi_commande){?>
                              <a style="margin-left: 1px" href="javascript:void(0);" data-href="<?= site_url('administrator/pos_store_2_ibi_commande/delete/' . $pos_store_2_ibi_commande->commande_id); ?>" class="btn btn-danger btn-xs remove-data"><i class="fa fa-close"></i></a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($pos_store_2_ibi_commande_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Pos Store 2 Ibi Commande data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'commande_numero' ? 'selected' :''; ?> value="commande_numero">Commande Numero</option>
                           <option <?= $this->input->get('f') == 'commande_article' ? 'selected' :''; ?> value="commande_article">Commande Article</option>
                           <option <?= $this->input->get('f') == 'commande_client_id' ? 'selected' :''; ?> value="commande_client_id">Commande Client Id</option>
                           <option <?= $this->input->get('f') == 'commande_user_id' ? 'selected' :''; ?> value="commande_user_id">Commande User Id</option>
                           <option <?= $this->input->get('f') == 'commande_categorie_id' ? 'selected' :''; ?> value="commande_categorie_id">Commande Categorie Id</option>
                           <option <?= $this->input->get('f') == 'commande_unite' ? 'selected' :''; ?> value="commande_unite">Commande Unite</option>
                           <option <?= $this->input->get('f') == 'delai' ? 'selected' :''; ?> value="delai">Delai</option>
                           <option <?= $this->input->get('f') == 'validite' ? 'selected' :''; ?> value="validite">Validite</option>
                           <option <?= $this->input->get('f') == 'a_la_commande' ? 'selected' :''; ?> value="a_la_commande">A La Commande</option>
                           <option <?= $this->input->get('f') == 'a_la_livraison' ? 'selected' :''; ?> value="a_la_livraison">A La Livraison</option>
                           <option <?= $this->input->get('f') == 'commande_date' ? 'selected' :''; ?> value="commande_date">Commande Date</option>
                           <option <?= $this->input->get('f') == 'commande_date_modification' ? 'selected' :''; ?> value="commande_date_modification">Commande Date Modification</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/pos_store_2_ibi_commande');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_pos_store_2_ibi_commande').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/pos_store_2_ibi_commande/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>