<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
   //This page is a result of an autogenerated content made by running test.html with firefox.
   function domo() {

      // Binding keys
      $('*').bind('keydown', 'Ctrl+a', function assets() {
         window.location.href = BASE_URL + '/administrator/requisition/add';
         return false;
      });

      $('*').bind('keydown', 'Ctrl+f', function assets() {
         $('#sbtn').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+x', function assets() {
         $('#reset').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+b', function assets() {

         $('#reset').trigger('click');
         return false;
      });
   }

   jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h3>
      <?= $this->model_rm->getOne('pos_ibi_stores', array('STATUS_STORE' => 'opened', 'ID_STORE' => $this->uri->segment(2)))['NAME_STORE'] ?> <i class="fa fa-chevron-right "></i>requisition<small></small>
   </h3>
   <h5 class="widget-user-desc">liste <i class="label bg-yellow"><?= $req_counts; ?> <?= cclang('items'); ?></i></h5>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Requisition</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row">

      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <form name="form_req" id="form_req" action="<?= base_url('requisition/' . $this->uri->segment(2) . '/index'); ?>">

                     <div class="widget-user-header row" style="border: 0px solid;">

             

                        <div class="col-md-7" style="border:0px solid;">
                           <div class="col-md-12">
                           <div class="row">
                              <div class="col-md-4">
                                 <div class="input-group">
                                    <span class="input-group-addon"><b>Debut</b></span>
                                    <input type="date" name="date_start" class="form-control">
                                 </div>
                              </div>

                              <div class="col-md-4">
                                 <div class="input-group">
                                    <span class="input-group-addon"><b>Fin</b></span>
                                    <input type="date" name="date_end" class="form-control">
                                 </div>
                              </div>

                              <div class="col-md-4">
                                 <select class="form-control" name="status_on">
                                    <option value="">Selectionner le status</option>
                                    <option value="0"> En Attente</option>
                                    <option value="1"> En Cours</option>
                                    <option value="3"> Approuver</option>
                                    <!--                                <option value="3"> Rejeter</option>
 -->
                                 </select>
                              </div>
                           </div>
                           </div>
                        </div>


                        <div class="col-md-3" style="border:0px solid;">
                           <div>
                              <input style="margin-right: 11px;" type="text" class="form-control" name="q" id="filter" placeholder="Rechercher" value="<?= $this->input->get('q'); ?>">
                           </div>
                        </div>


                        <div class="col-sm-2" style="border:0px solid;">

                           <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                              <i class="fa fa-search"></i>

                           </button>

                           <?php is_allowed('req_add', function () { ?>
                                 <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Pos Ibi Requisition']); ?>  (Ctrl+a)" href="<?= site_url('requisition/' . $this->uri->segment(2) . '/add'); ?>"><i class="fa fa-plus"></i> </a>
                              <?php }) ?>
                        </div>

                     </div>



                     <br>
                     <div class="table-responsive">
                        <table class="table table-bordered table-striped dataTable" id="table_requisition_ibs">
                           <thead>
                              <tr class="">
                                 <!-- <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th> -->
                                 <th>No</th>
                                 <th>Code Requisition</th>
                                 <th>Titre Requisition</th>
                                 <th>Provenance De</th>
                                 <th>VERS</th>
                                 <th>Status Requisitin</th>
                                 <th>Creer par</th>
                                 <th>Date Creation</th>
                                 <th>Actions</th>

                              </tr>
                           </thead>
                           <tbody id="tbody_req">
                              <?php $n = 0;
                              foreach ($requisition as $req) : $n++; ?>
                                 <tr>
                                    <!-- <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $req->ID_REQ; ?>">
                           </td> -->
                                    <td><?= $n; ?></td>
                                    <td><?= _ent($req->CODE_REQ); ?></td>
                                    <td><?= _ent($req->TITLE_REQ); ?></td>
                                    <td><?= $this->model_rm->getOne('pos_ibi_stores', array('STATUS_STORE' => 'opened', 'ID_STORE' => $req->FROM_STORE))['NAME_STORE'] ?></td>
                                    <td><?= !empty($this->model_rm->getOne('pos_ibi_stores', array('STATUS_STORE' => 'opened', 'ID_STORE' => $req->DESTINATION_STORE_REQ))['NAME_STORE']) ?

                                             $this->model_rm->getOne('pos_ibi_stores', array('STATUS_STORE' => 'opened', 'ID_STORE' => $req->DESTINATION_STORE_REQ))['NAME_STORE']

                                             : 'TOUTES' ?></td>

                                    <td id="that_btn_only"><?php if ($req->STATUS_REQ == 0) {
                                                               echo "<i class='label bg-blue'>En attente..</i>";
                                                            } elseif ($req->STATUS_REQ == 1) {
                                                               echo "<i class='label bg-orange'>Encours...</i>";
                                                            } elseif ($req->STATUS_REQ == 2) {
                                                               echo "<i class='label bg-green'>Approuvé</i>";
                                                            /*} elseif ($req->STATUS_REQ == 3) {
                                                               echo "<i class='label bg-aqua'>Approuvé...</i>";*/
                                                            
                                                            } elseif ($req->STATUS_REQ == 4) {
                                                               echo "<i class='label bg-aqua'>rejetée...</i>";
                                                            }
                                                            elseif ($req->STATUS_REQ == 6) {
                                                               echo "<i class='label bg-blue'>Approvisionné...</i>";
                                                            } ?>

                                    </td>

                                    <td>
                                       <?php $users = $this->model_rm->getOne('aauth_users', array('id' => $req->CREATED_BY_REQ)); ?>
                                       <?= _ent($users['full_name']); ?>
                                    </td>
                                    <td><?= _ent($req->DATE_CREATION_REQ); ?></td>
                                    <td width="140">

                                          <!-- <a title="ouvrir" style="margin-right: 2px" href="<?= site_url('requisition/' . $this->uri->segment(2) . '/view/' . $req->ID_REQ); ?>" id="<?php echo $req->ID_REQ; ?>" <?php if (($req->CREATED_BY_REQ!=get_user_data('id')) && $this->aauth->is_allowed('voir_detail_requisition')) { ?> onclick="bs_Viewer(this)" <?php } ?>class="btn btn-warning btn-xs"><i class="fa fa-eye-slash"></i></a> -->

                                          <a title="ouvrir" style="margin-right: 2px" href="<?= site_url('requisition/' . $this->uri->segment(2) . '/view/' . $req->ID_REQ); ?>" id="<?php echo $req->ID_REQ; ?>" class="btn btn-warning btn-xs"><i class="fa fa-eye-slash"></i></a>

                                     
                                          <?php if ($req->STATUS_REQ == 0) { ?>
                                           <?php is_allowed('requisition_userModify', function () use ($req) { ?>

                                             <a title="Ajouter ..." href="<?= site_url('requisition/' . $this->uri->segment(2) . '/edit/' . $req->ID_REQ); ?>" class="btn btn-info btn-xs"><i class="fa fa-plus-circle"></i> </a>

                                           <?php }) ?>
                                          <?php } ?>

                                       <!-- access denied start -->

                                       <div class="modal fade" id="alertModifier" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                          <div class="modal-dialog" role="document">
                                             <div class="modal-content">

                                                <div class="modal-body text-center">
                                                   <h3 class="modal-title" id="exampleModalLabel">Access Denied</h3>

                                                </div>
                                                <div class="modal-footer">
                                                   <button type="button" class="btn btn-info" data-dismiss="modal">Fermer</button>
                                                </div>
                                             </div>
                                          </div>
                                       </div>

                                       <!-- access denied end -->



                                    <?php if ($req->STATUS_REQ == 0) { ?>

                              <a title="annuler" href="javascript:void(0);" data-href="<?= site_url('administrator/requisition/deletes/' . $this->uri->segment(2) . '/' . $req->ID_REQ); ?>" class="btn btn-danger btn-xs  remove-data"><i class="fa fa-ban"></i></a>

                               <?php  } ?>
                                    </td>
                                 </tr>
                              <?php endforeach; ?>
                              <?php if ($req_counts == 0) : ?>
                                 <tr>
                                    <td colspan="100">
                                       Aucune requisition disponible
                                    </td>
                                 </tr>
                              <?php endif; ?>
                           </tbody>
                        </table>
                     </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">

                  </form>
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate">
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
   $(document).ready(function() {

      $('.remove-data').click(function() {

         var url = $(this).attr('data-href');

         swal({
               title: "Suppression ",
               text: "Vous etes sur le point de suprimer cette article!!..",
               type: "input",
               showCancelButton: true,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "Oui, supprimer",
               cancelButtonText: "Non, annuler",
               closeOnConfirm: false,
               closeOnCancel: true,
               animation: "slide-from-top",
               inputPlaceholder: "Donnez un commentaire S.V.P."
            },
            function(isConfirm) {
               if (isConfirm == "") {
                  swal.showInputError("Vous devriez ecrire un commentaire SVP.!!!");
                  return false;
               } else {


                  // swal.closeOnCancel = true;
                  document.location.href = url + '?inputValue=' + isConfirm;
                  //  document.location.href = url+'/'+isConfirm;   
                  // console.log(url+'/'+isConfirm); 
               }
            });

         return false;
      });










      $('#apply').click(function() {

         var bulk = $('#bulk');
         var serialize_bulk = $('#form_req').serialize();

         if (bulk.val() == 'delete') {
            swal({
                  title: "<?= cclang('are_you_sure'); ?>",
                  text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
                  type: "input",
                  inputPlaceholder: 'veillez signaler la raison de la suppresion',
                  showCancelButton: true,
                  confirmButtonColor: "#DD6B55",
                  confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
                  cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
                  closeOnConfirm: true,
                  closeOnCancel: true
               },
               function(isConfirm) {
                  if (isConfirm) {
                     console.log(serialize_bulk);
                     return
                     document.location.href = BASE_URL + '/administrator/requisition/delete?' + serialize_bulk;
                  }

               });

            return false;

         } else if (bulk.val() == '') {
            swal({
               title: "Upss",
               text: "<?= cclang('please_choose_bulk_action_first'); ?>",
               type: "warning",
               showCancelButton: false,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "Okay!",
               closeOnConfirm: true,
               closeOnCancel: true
            });

            return false;
         }

         return false;

      }); /*end appliy click*/


      //check all
      var checkAll = $('#check_all');
      var checkboxes = $('input.check');

      checkAll.on('ifChecked ifUnchecked', function(event) {
         if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
         } else {
            checkboxes.iCheck('uncheck');
         }
      });

      checkboxes.on('ifChanged', function(event) {
         if (checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
         } else {
            checkAll.removeProp('checked');
         }
         checkAll.iCheck('update');
      });

   }); /*end doc ready*/





   function bs_Viewers(th) {


      let ider = $(th).attr('id');
      $.ajax({
         url: BASE_URL + 'administrator/requisition/incomming/' + ider,
         type: 'get',
         data: {
            ider: ider
         },
         success: function(dt) {
            if (dt) {
               //  location.reload(true);
               //  $('#tbody_req').load('#tbody_req');
            } else {
               location.reload(true);
            }
         }
      });
   }


   function requisitionnerAdd(th) {
      let url = $(th).attr('data-href');
      //  alert(url);
      //  return false;

      swal({
            title: "message",
            text: "la confirmation se fait lorsque vous avez deja confirmer les articles de cette requisition! ",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "confirmer!",
            cancelButtonText: "Non!",
            closeOnConfirm: true,
            closeOnCancel: true
         },
         function(isConfirm) {

            $.ajax({
               url: url,
               method: 'post',
               dataType: 'json',
               data: {
                  "<?php echo $this->security->get_csrf_token_name(); ?> ": " <?php echo $this->security->get_csrf_hash(); ?>"
               },
               success: function(data) {
                  $('#table_approvisionnement_detail').load(' #table_approvisionnement_detail');
                  console.log(data);
               }
            })

            //  alert(quantite);


         }

      );

   }






   $(document).ready(function() {
      $(".table").load(document);
   });






   function refresherTable() {

   }

   setInterval(refresherTable, 2000);
</script>