<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
   //This page is a result of an autogenerated content made by running test.html with firefox.
   function domo() {

      // Binding keys
      $('*').bind('keydown', 'Ctrl+a', function assets() {
         window.location.href = BASE_URL + '/administrator/pos_categorie_depense/add';
         return false;
      });

      $('*').bind('keydown', 'Ctrl+f', function assets() {
         $('#sbtn').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+x', function assets() {
         $('#reset').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+b', function assets() {

         $('#reset').trigger('click');
         return false;
      });
   }

   jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Categorie Depense </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Categorie Depense</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row">

      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->


               <form name="form_pos_categorie_depense" id="form_pos_categorie_depense" action="<?= base_url('categorieDepense/index'); ?>">

                  <!-- /.widget-user -->
                  <div class="row">

                     <div class="col-sm-6 col-md-2" style=""></div>
                     <div class="col-sm-12 col-md-10" style="float: right;">
                        <div class="col-sm-3 padd-left-0"></div>

                        <div class="col-sm-5 padd-left-0">
                           <input type="text" class="form-control" name="q" id="filter" placeholder="<?= 'Recherher'; ?>" value="<?= $this->input->get('q'); ?>">
                        </div>

                        <div class="col-sm-4">
                           <input type="hidden" name="f" id="field">
                           <div class="col-sm-2 padd-left-0 ">
                              <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                                 <i class="fa fa-search"></i>
                              </button>
                           </div>

                           <div class="col-sm-2 padd-left-0 ">
                              <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="http://localhost:80/pos_zanzi/administrator/labo_examens" title="Réinitialiser la recherche">
                                 <i class="fa fa-undo"></i>
                              </a>
                           </div>
                           <div class="col-sm-8">
                              <?php is_allowed('pos_categorie_depense_add', function () { ?>
                                 <a class="btn btn-flat btn-success btn_add_new"  data-toggle="modal" data-target="#exampleModal" id="btn_add_new" title="ajout categorie  (Ctrl+a)" href="javascript:void(0)"><i class="fa fa-plus-circle" aria-hidden="true"></i> </a>


                              <?php }) ?>
                              <?php is_allowed('pos_categorie_depense_export', function () { ?>
                                 <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Pos Categorie Depense" href="<?= site_url('administrator/pos_categorie_depense/export'); ?>"><i class="fa fa-file-excel-o"></i> </a>
                              <?php }) ?>
                              <?php is_allowed('pos_categorie_depense_export', function () { ?>
                                 <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Pos Categorie Depense" href="<?= site_url('administrator/pos_categorie_depense/export_pdf'); ?>"><i class="fa fa-file-pdf-o"></i> </a>
                              <?php }) ?>

                           </div>
                        </div>
                     </div>
                  </div>


            </div>
            <hr>
            <div class="table-responsive row">
               <table class="table table-bordered table-striped dataTable" id="cat_depense">
                  <thead>
                     <tr class="">
                        <th>
                           <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                        </th>
                        <th>No</th>
                        <th>Designation Categorie Dep..</th>
                        <th>Depense Creer Par</th>
                        <th>Date Creation Categorie Dep.</th>
                        <th>Action</th>
                     </tr>
                  </thead>
                  <tbody id="tbody_pos_categorie_depense">
                     <?php $n = 0;
                     foreach ($pos_categorie_depenses as $pos_categorie_depense) : $n++; ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $pos_categorie_depense->ID_CATEGORIE_DEPENSE; ?>">
                           </td>
                           <td> <?= $n; ?></td>
                           <td><?= _ent($pos_categorie_depense->NOM_CATEGORIE_DEPENSE); ?></td>

                           <td><?php echo
                                 $user = $this->db->query('SELECT * FROM aauth_users WHERE id = "' . $pos_categorie_depense->CREATE_BY_CATEGORIE_DEPENSE . '" ')->row_array()['full_name'];
                                 ?>
                           </td>

                        <td><?= _ent($pos_categorie_depense->DATE_CREATE_CATEGORIE_DEPENSE); ?></td>
                           <td width="200">
                              <?php is_allowed('pos_categorie_depense_view', function () use ($pos_categorie_depense) { ?>
                                 <a style="margin-right: 2px" href="<?= site_url('categorieDepense/view/' . $pos_categorie_depense->ID_CATEGORIE_DEPENSE); ?>" class="btn btn-warning btn-xs"><i class="fa fa-eye-slash"></i></a>
                              <?php }) ?>
                              <?php is_allowed('pos_categorie_depense_update', function () use ($pos_categorie_depense) { ?>

                                    <a type="button" title="modification" onclick="get_cat_depenses(this)"
                                    id="<?php echo $pos_categorie_depense->ID_CATEGORIE_DEPENSE; ?>"
                                    class="btn btn-info btn-xs get_mod" data-toggle="modal"
                                    data-target="#exampleModal_up"> <i class="fa fa-pencil-square-o"
                                       aria-hidden="true"></i> </a>

                              <?php }) ?>
                              <?php is_allowed('pos_categorie_depense_delete', function () use ($pos_categorie_depense) { ?>
                                 <a href="javascript:void(0);" data-href="<?= site_url('administrator/pos_categorie_depense/delete/' . $pos_categorie_depense->ID_CATEGORIE_DEPENSE); ?>" class="btn btn-danger btn-xs remove-data"><i class="fa fa-close"></i></a>
                              <?php }) ?>
                           </td>
                        </tr>
                     <?php endforeach; ?>
                     <?php if ($pos_categorie_depense_counts == 0) : ?>
                        <tr>
                           <td colspan="100">
                              Donnees non disponble...
                           </td>
                        </tr>
                     <?php endif; ?>
                  </tbody>
               </table>
            </div>
         </div>
         <hr>

         </form>
         <div class="row">
            <div class="col-md-4" style="float:right">
               <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate">
                  <?= $pagination; ?>
               </div>
            </div>
         </div>

      </div>
      <!--/box body -->
   </div>
   <!--/box -->
   </div>
   </div>
</section>



<div class="modal fade" id="exampleModal_up" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
       <h5 class="modal-title update_title"  id="exampleModalLabel">Modification</h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          

   <?= form_open('', [
              'name'    => 'form_pos_categorie_up',
              'class'   => 'form-horizontal',
              'id'      => 'form_pos_categorie_up',
              'enctype' => 'multipart/form-data',
              'method'  => 'POST'
            ]); ?>

            <div class="form-group ">
              <label for="NOM_CATEGORIE_DEPENSE" class="col-sm-3 control-label">Nom categorie
                <i class="required">*</i>
              </label>
              <div class="col-sm-9">
                <input type="text" class="form-control" name="NOM_CATEGORIE_DEPENSE_UP" id="NOM_CATEGORIE_DEPENSE_UP" placeholder="NOM CATEGORIE DEPENSE" value="">
                <input type="hidden" name="ID_CATEGORIE_DEPENSE_UP" id="ID_CATEGORIE_DEPENSE_UP" value="">
                <input type="hidden" name="URI" value="<?= $this->uri->segment(2); ?>">

              </div>
            </div>

            <br>
            <div class="message"></div>
            <div class="row-fluid col-md-7">
             
         

              <a class="btn btn-flat btn-info btn_editer btn_action btn_save_back" id="btn_editer" data-stype='back' title="modification">
                <i class="ion ion-ios-list-outline"></i> Modifiez
              </a>


              <a class="btn btn-flat btn-default btn_action" id="btn_cancel" data-dismiss="modal" title="Retour (Ctrl+x)">
                <i class="fa fa-undo"></i> Retour
              </a>
              <span class="loading loading-hide">
                <img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg">
                <i><?= cclang('loading_saving_data'); ?></i>
              </span>
            </div>
            <?= form_close(); ?>


      </div>
      <div class="modal-footer">
      
      </div>
    </div>
  </div>
</div>





<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title add_title" id="exampleModalLabel">Ajout de la categorie depense</h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          

   <?= form_open('', [
              'name'    => 'form_pos_categorie_add',
              'class'   => 'form-horizontal',
              'id'      => 'form_pos_categorie_add',
              'enctype' => 'multipart/form-data',
              'method'  => 'POST'
            ]); ?>

            <div class="form-group ">
              <label for="NOM_CATEGORIE_DEPENSE" class="col-sm-3 control-label">Nom categorie
                <i class="required">*</i>
              </label>
              <div class="col-sm-9">
                <input type="text" class="form-control" name="NOM_CATEGORIE_DEPENSE" id="NOM_CATEGORIE_DEPENSE" placeholder="NOM CATEGORIE DEPENSE" value="">
                <input type="hidden" name="ID_CATEGORIE_DEPENSE" id="ID_CATEGORIE_DEPENSE" value="">
                <input type="hidden" name="URI" value="<?= $this->uri->segment(2); ?>">

              </div>
            </div>

            <br>
            <div class="message"></div>
            <div class="row-fluid col-md-7">
             
              <a class="btn btn-flat btn-info btn_save btn_action btn_save_back" id="btn_save" data-stype='back' title="<?= cclang('save_and_go_the_list_button'); ?> (Ctrl+d)">
                <i class="ion ion-ios-list-outline"></i> Enregistrez
              </a>




              <a class="btn btn-flat btn-default btn_action" id="btn_cancel" data-dismiss="modal" title="Retour (Ctrl+x)">
                <i class="fa fa-undo"></i> Retour
              </a>
              <span class="loading loading-hide">
                <img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg">
                <i><?= cclang('loading_saving_data'); ?></i>
              </span>
            </div>
            <?= form_close(); ?>


      </div>
      <div class="modal-footer">
      
      </div>
    </div>
  </div>
</div>



<!-- /.content -->

<!-- Page script -->
<script>




   $('.btn-default').click(function() {
      $('#NOM_CATEGORIE_DEPENSE').val("");
   })


   $(document).ready(function() {

      $('.remove-data').click(function() {
         // alert('ddd')

         var url = $(this).attr('data-href');

         swal({
               title: "Message",
               text: "La suppression se fait une seule fois",
               type: "input",
               showCancelButton: true,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
               cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
               closeOnConfirm: true,
               closeOnCancel: true,
               animation: "slide-from-top",
               inputPlaceholder: "Donnez un commentaire S.V.P."
            },
            function(inputValue) {
               if (inputValue === false) {
                  return false;
               }
               if (inputValue === "") {
                  swal.showInputError("Vous devriez ecrire un commentaire SVP.!!!");
                  return false;
               }
               document.location.href = url + '?inputValue=' + inputValue;
            },
            function(isConfirm) {
               // if (isConfirm) {
               //    document.location.href = BASE_URL + '/administrator/pos_categorie_depense/delete?' + serialize_bulk;      
               // }
            });

         return false;
      });





    $('.btn_save').click(function() {

      let name  = $('#NOM_CATEGORIE_DEPENSE').val();
      // alert(name);
      $('.message').fadeOut();

      var form_pos_categorie_add = $('#form_pos_categorie_add');
      var data_post = form_pos_categorie_add.serializeArray();
      var save_type = $(this).attr('data-stype');

      data_post.push({
        name: 'save_type',
        value: save_type
      });

      $('.loading').show();

      $.ajax({
          url: BASE_URL + '/administrator/pos_categorie_depense/add_save',
          type: 'POST',
          dataType: 'json',
          data: data_post,
        })
        .done(function(res) {
          if (res.success) {

               $('#cat_depense').load(' #cat_depense');
               $('#exampleModal').modal('hide');
               $('.message').css('display', 'none');

               swal({
                  title: "success",
                  text: "Categorie ajouter",
                  type: "success",
                  confirmButtonColor: "#green",
                  confirmButtonText: "Oui!",
                  timer: 1000,
                  closeOnConfirm: true,
               });

                     $('#NOM_CATEGORIE_DEPENSE').val();



          } else {
            $('.message').printMessage({
              message: res.message,
              type: 'warning'
            });
          }

        })
        .fail(function() {
          $('.message').printMessage({
            message: 'Error save data',
            type: 'warning'
          });
        })
        .always(function() {
          $('.loading').hide();
          $('html, body').animate({
            scrollTop: $(document).height()
          }, 2000);
        });

      return false;
    }); /*end btn save*/


 




 


      $('#apply').click(function() {

         var bulk = $('#bulk');
         var serialize_bulk = $('#form_pos_categorie_depense').serialize();

         if (bulk.val() == 'delete') {
            swal({
                  title: "<?= cclang('are_you_sure'); ?>",
                  text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
                  type: "input",
                  showCancelButton: true,
                  confirmButtonColor: "#DD6B55",
                  confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
                  cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
                  closeOnConfirm: true,
                  closeOnCancel: true,
                  animation: "slide-from-top",
                  inputPlaceholder: "Donnez un commentaire S.V.P."
               },
               function(inputValue) {
                  if (inputValue === false) {
                     return false;
                  }
                  if (inputValue === "") {
                     swal.showInputError("Vous devriez ecrire un commentaire SVP.!!!");
                     return false;
                  }
                  document.location.href = url + '?inputValue=' + inputValue;
               },
               function(isConfirm) {
                  // if (isConfirm) {
                  //    document.location.href = BASE_URL + '/administrator/pos_categorie_depense/delete?' + serialize_bulk;      
                  // }
               });

            return false;

         } else if (bulk.val() == '') {
            swal({
               title: "Upss",
               text: "<?= cclang('please_choose_bulk_action_first'); ?>",
               type: "warning",
               showCancelButton: false,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "Okay!",
               closeOnConfirm: true,
               closeOnCancel: true
            });

            return false;
         }

         return false;

      }); /*end appliy click*/


      //check all
      var checkAll = $('#check_all');
      var checkboxes = $('input.check');

      checkAll.on('ifChecked ifUnchecked', function(event) {
         if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
         } else {
            checkboxes.iCheck('uncheck');
         }
      });

      checkboxes.on('ifChanged', function(event) {
         if (checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
         } else {
            checkAll.removeProp('checked');
         }
         checkAll.iCheck('update');
      });

   }); /*end doc ready*/
</script>





<script type="text/javascript">
   
    function get_cat_depenses(th){

      
  let id = $(th).attr('id');

      $.ajax({
         url: BASE_URL + '/administrator/pos_categorie_depense/get_categori_depenses',
         type: 'POST',
         dataType: 'json',
         data: {
            id: id
         },
         success: function(dt) {
            console.log(dt);
            $("#ID_CATEGORIE_DEPENSE_UP").val(dt.ID_CATEGORIE_DEPENSE);
            $("#NOM_CATEGORIE_DEPENSE_UP").val(dt.NOM_CATEGORIE_DEPENSE);

         }
      })

 }









   $('.btn_editer').click(function() {
      $('.message').fadeOut();

      var form_pos_categorie_up = $('#form_pos_categorie_up');
      var data_post = form_pos_categorie_up.serializeArray();
      var save_type = $(this).attr('data-stype');
      let id = $('#ID_CATEGORIE_DEPENSE_UP').val();
      // alert(id);return false;

      data_post.push({
         name: 'save_type',
         value: save_type
      });
      $('.loading').show();

      $.ajax({
            url: BASE_URL + '/administrator/pos_categorie_depense/edit_save/' + id,
            type: 'POST',
            dataType: 'json',
            data: data_post,
         })
         .done(function(res) {
            if (res.success) {

               $('#cat_depense').load(' #cat_depense');
               $('#exampleModal_up').modal('hide');
               $('.message').css('display', 'none');

               swal({
                  title: "success",
                  text: "Modification faite",
                  type: "success",
                  confirmButtonColor: "#green",
                  confirmButtonText: "Oui!",
                  timer: 1000,
                  closeOnConfirm: true,
               });

               // $('.message').fadeOut();



               if (save_type == 'back') {
                  // window.location.href = res.redirect;
                  return;
               }


               resetForm();
               $('.chosen option').prop('selected', false).trigger('chosen:updated');

            } else {
               $('.message').printMessage({
                  message: res.message,
                  type: 'warning'
               });
            }

         })
         .fail(function() {
            $('.message').printMessage({
               message: 'Error save data',
               type: 'warning'
            });
         })
         .always(function() {
            $('.loading').hide();
            $('html, body').animate({
               scrollTop: $(document).height()
            }, 2000);
         });

      return false;
   }); /*end btn save*/


</script>