<script>

  $(function() {

    $('.chosen-select').chosen();

    $('.chosen-select-deselect').chosen({

      allow_single_deselect: true

    });

  });

</script>



<style>

  .list-group-item:hover {

    background-color: #cccccc4a !important;

    cursor: pointer;

  }

</style>



<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>



<script type="text/javascript">

  //This page is a result of an autogenerated content made by running test.html with firefox.

  function domo() {



    // Binding keys

    $('*').bind('keydown', 'Ctrl+a', function assets() {

      window.location.href = BASE_URL + '/administrator/pos_ibi_commandes/add';

      return false;

    });



    $('*').bind('keydown', 'Ctrl+f', function assets() {

      $('#sbtn').trigger('click');

      return false;

    });



    $('*').bind('keydown', 'Ctrl+x', function assets() {

      $('#reset').trigger('click');

      return false;

    });



    $('*').bind('keydown', 'Ctrl+b', function assets() {



      $('#reset').trigger('click');

      return false;

    });

  }



  jQuery(document).ready(domo);

</script>

<!-- Content Header (Page header) -->

<section class="content-header">

  <h1>

   Facture déjà imprimé </h1>

  <ol class="breadcrumb">

    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>

    <li class="active">Facture déjà imprimé</li>

  </ol>

</section>

<!-- Main content -->

<section class="content">

  <div class="row">



    <div class="col-md-12">

      <div class="box box-warning">

        <div class="box-body ">

          <!-- Widget: user widget style 1 -->





          <form name="form_pos_ibi_commandes" id="form_pos_ibi_commandes" action="<?= base_url('administrator/pos_ibi_commandes/void_to_request'); ?>">



            <!-- /.widget-user -->

            <div class="row">



              

              <div class="col-sm-12 col-md-12" style="float:;">







                 <div class="col-lg-4 col-md-4 col-sm-4">

                         

                             <div class="input-group">

                           <div class="input-group-addon">

                            DU 

                            </div>

                                <input type="date" name="DEBUT" class="form-control datepicker" value="<?php if($start!=''){echo $start; } ?>">

                            </div>

                      </div>   



                       <div class="col-lg-4 col-md-4 col-sm-4">

                         

                             <div class="input-group">

                           <div class="input-group-addon">

                            AU 

                            </div>

                                <input type="date" name="FIN" class="form-control datepicker" value="<?php if($end!=''){ echo $end; }

                                ?>">

                            </div>

                      </div>

 







               



                <div class="col-sm-2" style="border: 0px solid;">

                  <input type="hidden" name="f" id="field">

                  <div class="col-sm-12 padd-left-0 ">

                    <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">

                      <i class="fa fa-search"></i>

                    </button>

                  

                    <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= site_url('administrator/pos_ibi_commandes/facture_imprimer'); ?>" title="Réinitialiser la recherche">

                      <i class="fa fa-undo"></i>

                    </a>

                  



                </div>

              </div>

            </div>



          </div>

          <br/>



          </form>



          <br>



          <div id="confirmedit" style="display: none" class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

            <div class="modal-dialog" role="document">

              <div class="modal-content">

                <div class="modal-header">

                  <h3 class="modal-title" id="exampleModalLabel"> Choissez le type de modification</h3>

                </div>

                <div class="modal-body" style="display: flex;justify-content: space-around">

                  <button type="button" class="btn btn-info confirmEdit" data-type="1">

                    Ajouter à la commande

                  </button>

                  <button type="button" class="btn btn-success confirmEdit" data-type="2">Retirer à la commande</button>

                </div>

                <div class="modal-footer">

                  <button type="button" class="btn btn-secondary cancelEdit">Close</button>



                </div>

              </div>

            </div>

          </div>

          <div class="col-md-12">



            <div class="table-responsive row">

              <table class="table table-bordered table-striped dataTable" id="table_cmd">

                <thead>

                  <tr class="">

                    

                    <th>Code</th>

                    <th>Client</th>

                    <!-- <th>Status</th> -->

                    <!-- <th>Montant</th> -->

                    <th>Date creation</th>

                    <th>Creer par</th>

                    <th>Date impression</th>

                    <th>Imprimé par</th>

                    <th>Action</th>

                  </tr>

                </thead>

                <tbody id="tbody_pos_ibi_commandes">

                  <?php foreach ($pos_ibi_commandess as $pos_ibi_commandes) : ?>

                    <tr>

                     



                      <td><?= _ent($pos_ibi_commandes->CODE); ?></td>

                      <td><?php

                          $id_client = _ent($pos_ibi_commandes->CLIENT_ID_COMMANDE);

                          $query = $this->db->get_where('pos_clients', array('ID_CLIENT' => $id_client))->row();

                          echo $query->NOM_CLIENT . '  ' . $query->PRENOM;

                          ?></td>

                      <td>

                        <?php



                        $status_delete = $pos_ibi_commandes->DELETED_STATUS_POS_IBI_COMMANDES;

                        $status = $pos_ibi_commandes->COMMANDE_STATUS;

                        // if ($status_delete==1) {

                        //   echo '<p class="bg-red badge">Supprimé</p>';

                        // }

                        // else{

                        if ($status == 0) {

                          echo '<p class="bg-yellow badge">Impayer</p>';

                        } elseif ($status == 1) {

                          echo '<p class="bg-blue badge">En avance</p>';

                        } elseif ($status == 2) {

                          echo '<p class="bg-green badge">Complete</p>';

                        } elseif ($status == 11) {

                          echo '<p class="bg-green badge">Complementaire</p>';

                        } elseif ($status == 10) {

                          echo '<p class="bg-red badge">Credit</p>';

                        } else {

                          echo '<p class="bg-blue badge">Encours</p>';

                        }



                       //}



                        ?>

                      </td>



                     <!--  <td><?//= _ent($pos_ibi_commandes->PRIX_TOTAL); ?> Fbu</td> -->





                      <td><?= _ent($pos_ibi_commandes->DATE_CREATION_POS_IBI_COMMANDES); ?></td>

                      <td><?php

                          $id_user = _ent($pos_ibi_commandes->CREATED_BY_POS_IBI_COMMANDES);

                           echo get_name_user($id_user);

                          ?></td>



                          <td><?= _ent($pos_ibi_commandes->DELETED_DATE_POS_IBI_COMMANDES);

                          ?></td>



                           <td><?php

                          $id_user_delete = _ent($pos_ibi_commandes->DELETED_USER_POS_IBI_COMMANDES);

                           echo get_name_user($id_user_delete);

                         

                          ?></td>



                      <td width="100">

                        <?php $status = $pos_ibi_commandes->COMMANDE_STATUS; ?>

                        <?php //if ($status == 0) : ?>

                          <!-- <button data-cmdid="<?= $pos_ibi_commandes->POS_IBI_COMMANDES; ?>" style="margin-right: 2px" class="btn btn-warning btn-xs btnoptions"><i class="fa fa-plus"></i> <i class="fa fa-edit"></i></button> -->

                        <?php //endif; ?>

                        <button data-toggle="modal" data-target="#myModal<?= $pos_ibi_commandes->POS_IBI_COMMANDES; ?>" style="margin-right: 2px" data-title="facture" data-id="<?php echo $pos_ibi_commandes->POS_IBI_COMMANDES ?>" class="btn_produit_data btn btn-default btn-xs"><i class="fa fa-th-list"></i></button>

                        <?php is_allowed('pos_ibi_commandes_view', function () use ($pos_ibi_commandes) { ?>

                          <a style="margin-right: 2px" data-title="paiement" href="<?= site_url('administrator/pos_ibi_commandes/debloquer_facture/' . $pos_ibi_commandes->POS_IBI_COMMANDES); ?>" class="btn bg-green btn-xs" title="Debloquer"><i class="fa fa-arrow-left"></i></a>

                        <?php }) ?>

                      </td>

                    </tr>







                    <div id="myModal<?= $pos_ibi_commandes->POS_IBI_COMMANDES; ?>" class="modal fade" role="dialog">

                      <div id="fileToPrint" class="modal-dialog">

                        <!-- Modal content-->

                        <div class="modal-content">

                          <div class="modal-header">

                            <button type="button" class="close" data-dismiss="modal">&times;</button>

                            <h4 class="modal-title">Facture</h4>

                          </div>

                          <div class="modal-body" id="target_<?php echo $pos_ibi_commandes->POS_IBI_COMMANDES;  ?>">

                            <?php $clients = $this->db->get_where('pos_clients', array('ID_CLIENT' => $pos_ibi_commandes->CLIENT_ID_COMMANDE))->row(); ?>







                            <div class="body" style="margin-bottom:20px !important;width:100% !important">







                              <div>FACTURE : <?php echo $pos_ibi_commandes->CODE;  ?></div>

                              <hr>

                              <div><strong>A.IDENTIFICATION DU VENDEUR</strong></div>

                              <div><?php  echo settings_address()['tp_name']; ?></div>

                              <div> NIF: <?php  echo settings_address()['tp_TIN']; ?></div>

                              <div>RC:<?php  echo settings_address()['tp_trade_number']; ?></div>

                              <div>Commune:<?php  echo settings_address()['tp_address_commune']; ?></div>

                              <div>Quartier:<?php  echo settings_address()['tp_address_quartier'].' ,'.' ' .  settings_address()['tp_address_avenue']; ?></div>

                              <div><strong>B.CLIENTS</strong></div>

                              <span style="text-transform:uppercase">NOM :<?php echo $clients->NOM_CLIENT . ' ' . $clients->PRENOM; ?></span><br>

                              <span>Assujeti à la TVA: Non</span>

                              <div style="width: 100%;display:flex;justify-content: space-between; font-weight:bold;border-bottom: 1px solid #ccc">



                                <p style="width: 23rem">Designation</p>

                                <div style="display:flex;justify-content:space-between;flex-direction:row;flex:1">

                                  <p>Qté</p>

                                  <p>P</p>

                                  <p>R(%)</p>

                                  <p></p>

                                </div>

                              </div>

                              <?php $total = 0; ?>



                              <?php foreach ($pos_ibi_commandes->PRODUCTS as $prod) : ?>

                                <div style="width: 100%;display: flex;justify-content:space-between;padding-right:1px">

                                  <p style="width: 23rem;margin-bottom:0px"><?= $prod->NAME_PRODUIT; ?></p>

                                  <div style="display:flex;justify-content:space-between;flex-direction:row;flex:1">

                                    <p style="margin-bottom:0px"> <?= $prod->QUANTITE; ?></p>

                                    <p style="margin-bottom:0px"><?= number_format($prod->PRIX_VENDU); ?></p>

                                    <p style="margin-right:10px;margin-bottom:0px"><?= number_format($prod->DISCOUNT_PERCENT); ?></p>

                                    <!-- <p class="no"><?= number_format((($prod->QUANTITE * $prod->PRIX) - (($prod->QUANTITE * $prod->PRIX) * $prod->DISCOUNT_PERCENT / 100))); ?></p> -->

                                    <p></p>

                                  </div>

                                </div>

                                <?php $total += (($prod->QUANTITE * $prod->PRIX_VENDU) - (($prod->QUANTITE * $prod->PRIX_VENDU) * $prod->DISCOUNT_PERCENT / 100)); ?>

                              <?php endforeach; ?>

                              <div style="width: 100%;display: flex; justify-content: space-between; border-top: 1px solid #000;">

                                <p><strong>TOTAL</strong> :

                                <p style="text-align:center !important"><?= number_format($total); ?> Fbu</p>

                                </p>

                              </div>

                              <p>

                                <hr>

                              </p>



                            </div>

                          </div>

                          <div class="modal-footer">

                            <p class="btn btn-default print" data-attr="<?php echo $pos_ibi_commandes->POS_IBI_COMMANDES;   ?>">Imprimer</p>

                            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

                          </div>

                        </div>



                      </div>

                    </div>

                    <div id="myModalbon<?= $pos_ibi_commandes->POS_IBI_COMMANDES; ?>" class="modal fade" role="dialog">

                      <div id="fileToPrint" class="modal-dialog">

                        <!-- Modal content-->

                        <div class="modal-content">

                          <div class="modal-header">

                            <button type="button" class="close" data-dismiss="modal">&times;</button>

                            <h4 class="modal-title">Bons de commande</h4>

                          </div>

                          <div class="modal-body" id="targets_<?= $pos_ibi_commandes->POS_IBI_COMMANDES; ?>">

                            <div>





                              <?php foreach ($pos_ibi_commandes->BON as $bon_cmd) : ?>

                                <p>BON POUR : <strong><?php echo $bon_cmd[0]->NAME_STORE;  ?></strong></p>

                                <p>CODE COMMANDE: <?php echo $pos_ibi_commandes->BON[0][0]->REF_COMMAND_CODE;  ?></p>

                                <div style="width: 100%;display:flex;justify-content: space-between; font-weight:bold;border-bottom: 1px solid #ccc">

                                  <p style="width: 23rem">Designation</p>

                                  <p>Qté</p>

                                  <p>P.u</p>

                                  <p>Remise</p>

                                  <p>Total</p>

                                </div>

                                <?php foreach ($bon_cmd as $prod) : ?>

                                  <div style="width: 100%;display: flex;justify-content:space-between">

                                    <p style="width: 23rem"><?= $prod->NAME_PRODUIT; ?></p>

                                    <p><?= $prod->QUANTITE; ?></p>

                                    <p><?= $prod->PRIX_VENDU; ?></p>

                                    <p><?= $prod->DISCOUNT_PERCENT; ?></p>

                                    <p><?= (($prod->QUANTITE * $prod->PRIX_VENDU) - (($prod->QUANTITE * $prod->PRIX_VENDU) * $prod->DISCOUNT_PERCENT / 100)); ?></p>

                                  </div>

                                <?php endforeach; ?>

                                </br>

                                </hr>

                              <?php endforeach; ?>

                            </div>

                            </div>

                            <div class="modal-footer">

                              <button type="button" class="btn btn-default prints" data-attr="<?php echo $pos_ibi_commandes->POS_IBI_COMMANDES;   ?>">Imprimer</button>

                              <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

                            </div>

                          </div>



                        </div>

                      </div>

                    <?php endforeach; ?>

                    </div>

                    <div id="myModalclient" class="modal fade" role="dialog">

                      <div class="modal-dialog">

                        <!-- Modal content-->

                        <div class="modal-content">

                          <div class="modal-header">



                            <h4 class="modal-title">Transferer la commande</h4>

                          </div>

                          <div class="modal-body" id="target_<?php echo $pos_ibi_commandes->POS_IBI_COMMANDES;  ?>">

                            <div>

                              <div class="form-group">

                                <input placeholder="Recherche" type="text" class="form-control" id="clientFilter">

                              </div>

                              <ul style="height: 300px; overflow-y: scroll; " class="list-group" id="clientlist">



                              </ul>

                            </div>

                          </div>

                          <div class="modal-footer" id="clientfooter">



                          </div>

                        </div>



                      </div>

                    </div>

                    <?php if ($pos_ibi_commandes_counts == 0) : ?>

                      <tr>

                        <td colspan="100">

                          Pas de donnees disponible.

                        </td>

                      </tr>

                    <?php endif; ?>

                </tbody>

              </table>

            </div>

          </div>

          <hr>





          <div id="GSCCModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

            <div class="modal-dialog">

              <div class="modal-content">

                <div class="modal-header">

                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times; </button>

                  <h4 class="modal-title" id="myModalLabel">Listes des touts les Shifts</h4>

                </div>

                <div class="modal-body">

                  <input type="text" class="form-control" id="filters">

                  <br>

                  <ul class="list-group" id="item">

                  </ul>

                </div>

                <div class="modal-footer">

                  <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>

                  <button type="button" class="btn btn-primary">Confirmer</button>

                </div>

              </div>

            </div>

          </div>





          <div class="row">

            <div class="col-md-4" style="float:right">

              <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate">

                <?= $pagination; ?>

              </div>

            </div>

          </div>



        </div>

        <!--/box body -->

      </div>

      <!--/box -->

    </div>

  </div>

</section>



<script>

  var selectedCmdId = undefined;



  function setCmdId(id) {

    selectedCmdId = id;

  }

</script>



<script>

  const clientList = <?= $clients_list; ?>;

  let activeClient = undefined;



  (() => {

    console.log("onnnnnn...");

    $("#clientFilter").on('keyup', () => {

      const filter = $("#clientFilter").val();

      displayList(filter);

    });

  })();



  function confirmTransfert() {

    console.log("confirming...", activeClient, selectedCmdId);

    fetch(`<?= base_url(); ?>/administrator/pos_ibi_commandes/transfer_command/${activeClient}/${selectedCmdId}`)

      .then(data => data.json())

      .then(res => {

        window.location.reload();

      })

  }



  function cancelTransfert() {

    setTimeout(() => {

      activeClient = undefined;

      selectedCmdId = undefined;

      displayList("");

      $("#clientFilter").val("");

    }, 500);

    setTimeout(() => handleBtn(), 1000);

  }



  function handleBtn() {

    $("#clientfooter").html("");

    if (!!activeClient) {

      $("#clientfooter").append(` <button type="button" class="btn btn-default" onclick="confirmTransfert()" data-dismiss="modal">Confirmer</button><button type="button" onclick="cancelTransfert()" class="btn btn-default" data-dismiss="modal">Retour</button>`);;

    } else {

      $("#clientfooter").append(` <button type="button" class="btn btn-default" onclick="cancelTransfert()" data-dismiss="modal">Retour</button>`);

    }

  }



  handleBtn();





  function setCurrentClient(cl) {

    if (!!activeClient) {

      $(`#${activeClient}`).removeClass('active');

    }

    activeClient = cl;

    $(`#${cl}`).addClass('active');

    handleBtn();

  }



  function displayList(filter) {

    let todisplayList = '';

    $("#clientlist").html("");

    const filteredClients = clientList.filter(

      (c) => c.NOM_CLIENT.toLowerCase().match(filter.toLowerCase()) ||

      c.PRENOM.toLowerCase().match(filter.toLowerCase()));

    console.log(filteredClients);

    filteredClients.forEach(l => {

      todisplayList += `

      <li onclick="setCurrentClient(${l.ID_CLIENT})" class="list-group-item" id="${l.ID_CLIENT}">${l.NOM_CLIENT} ${l.PRENOM}</li>

      `;

    })

    $("#clientlist").append(todisplayList);

  }

  displayList("");

</script>



<script>

  $('.print').on('click', function() {

    const id = $(this).attr('data-attr');

    console.log(" Vous etes  " + id);

    var table = document.getElementById('target_' + id);

    // console.log(table);

    var ctx = table.outerHTML;

    var idname = name;

    var frame1 = document.createElement('iframe');

    frame1.name = "frame1";

    frame1.style.position = "absolute";

    frame1.style.top = "-1000000px";

    document.body.appendChild(frame1);

    var frameDoc = frame1.contentWindow ? frame1.contentWindow : frame1.contentDocument.document ? frame1

      .contentDocument.document : frame1.contentDocument;

    frameDoc.document.open();

    frameDoc.document.write('<html><head><title></title>');

    frameDoc.document.write(

      '<style>body{margin:10px !important}table {  border-collapse: collapse;  border-spacing: 0; width:100%; margin-top:20px;} .table td, .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th{ padding:8px 18px;border:1px  } .table-bordered, .table-bordered > tbody > tr > td, .table-bordered > tbody > tr > th, .table-bordered > tfoot > tr > td, .table-bordered > tfoot > tr > th, .table-bordered > thead > tr > td, .table-bordered > thead > tr > th {     border: 1px solid #000;}p + p { margin-left: 30px;}.body{width:100% !important}.no{display:none !important} </style>'

    ); // your title

    frameDoc.document.title = "Facture";

    frameDoc.document.write('<meta charset="utf-8"></head><body>');

    frameDoc.document.write(ctx);

    frameDoc.document.write('</body></html>');

    frameDoc.document.close();

    setTimeout(function() {

      window.frames["frame1"].focus();

      window.frames["frame1"].print();

      document.body.removeChild(frame1);

    }, 100);



  });

</script>



<script>

  $('.prints').on('click', function() {

    const id = $(this).attr('data-attr');

    console.log(" Vous etes  " + id);

    var table = document.getElementById('targets_' + id);

    // console.log(table);

    var ctx = table.outerHTML;

    var idname = name;

    var frame1 = document.createElement('iframe');

    frame1.name = "frame1";

    frame1.style.position = "absolute";

    frame1.style.top = "-1000000px";

    document.body.appendChild(frame1);

    var frameDoc = frame1.contentWindow ? frame1.contentWindow : frame1.contentDocument.document ? frame1

      .contentDocument.document : frame1.contentDocument;

    frameDoc.document.open();

    frameDoc.document.write('<html><head><title></title>');

    frameDoc.document.write(

      '<style>body{margin:10px !important}table {  border-collapse: collapse;  border-spacing: 0; width:100%; margin-top:20px;} .table td, .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th{ padding:8px 18px;border:1px  } .table-bordered, .table-bordered > tbody > tr > td, .table-bordered > tbody > tr > th, .table-bordered > tfoot > tr > td, .table-bordered > tfoot > tr > th, .table-bordered > thead > tr > td, .table-bordered > thead > tr > th {     border: 1px solid #000;}p + p { margin-left: 30px;}.body{width:100% !important}.no{display:none !important} </style>'

    ); // your title

    frameDoc.document.title = "Facture";

    frameDoc.document.write('<meta charset="utf-8"></head><body>');

    frameDoc.document.write(ctx);

    frameDoc.document.write('</body></html>');

    frameDoc.document.close();

    setTimeout(function() {

      window.frames["frame1"].focus();

      window.frames["frame1"].print();

      document.body.removeChild(frame1);

    }, 100);



  });

</script>





<script>

  var selectedcmd = undefined;

  $(document).ready(function() {



    console.log("okayl....");

    $('.btnoptions').click(function(e) {

      selectedcmd = $(this).data('cmdid');

      $("#confirmedit").show();

    });



    $('.confirmEdit').on('click', function() {

      const num = $(this).data('type');

      window.location.href = "<?= site_url('administrator/pointdesventes/update_commande/'); ?>" + selectedcmd + '/' + num;

    });

    $('.cancelEdit').on('click', function() {

      $("#confirmedit").hide();

    });





    $('.remove-data').click(function() {



      var url = $(this).attr('data-href');



      swal({

          title: "<?= cclang('are_you_sure'); ?>",

          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",

          type: "input",

          showCancelButton: true,

          confirmButtonColor: "#DD6B55",

          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",

          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",

          closeOnConfirm: true,

          closeOnCancel: true,

          animation: "slide-from-top",

          inputPlaceholder: "Donnez un commentaire S.V.P."

        },

        function(inputValue) {

          if (inputValue === false) {

            return false;

          }

          if (inputValue === "") {

            swal.showInputError("Vous devriez ecrire un commentaire SVP.!!!");

            return false;

          }

          document.location.href = url + '?inputValue=' + inputValue;

        },

        function(isConfirm) {

          // if (isConfirm) {

          // document.location.href = BASE_URL + '/administrator/pos_ibi_commandes/delete?' + serialize_bulk;

          // }

        });



      return false;

    });

  }); /*end doc ready*/

</script>