
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Commission      <small><?= cclang('detail', ['Commission']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/commission'); ?>">Commission</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Commission</h3>
                     <h5 class="widget-user-desc">Detail Commission</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_commission" id="form_commission" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID COMMISSION </label>

                        <div class="col-sm-8">
                           <?= _ent($commission->ID_COMMISSION); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">REF COMMAND CODE COMMISSION </label>

                        <div class="col-sm-8">
                           <?= _ent($commission->REF_COMMAND_CODE_COMMISSION); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">STATUT COMMISSION </label>

                        <div class="col-sm-8">
                           <?= _ent($commission->STATUT_COMMISSION); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MONTANT COMMISSION </label>

                        <div class="col-sm-8">
                           <?= _ent($commission->MONTANT_COMMISSION); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SELLER </label>

                        <div class="col-sm-8">
                           <?= _ent($commission->SELLER); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">APPROUVED BY COMMISSION </label>

                        <div class="col-sm-8">
                           <?= _ent($commission->APPROUVED_BY_COMMISSION); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CREATED BY COMMISSION </label>

                        <div class="col-sm-8">
                           <?= _ent($commission->CREATED_BY_COMMISSION); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DATE CREATION COMMISSION </label>

                        <div class="col-sm-8">
                           <?= _ent($commission->DATE_CREATION_COMMISSION); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">STORE COMMISSION </label>

                        <div class="col-sm-8">
                           <?= _ent($commission->TYPE_COMMISSION); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('commission_update', function() use ($commission){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit commission (Ctrl+e)" href="<?= site_url('administrator/commission/edit/'.$commission->ID_COMMISSION); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Commission']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/commission/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Commission']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
