<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
   //This page is a result of an autogenerated content made by running test.html with firefox.
   function domo() {

      // Binding keys
      $('*').bind('keydown', 'Ctrl+a', function assets() {
         window.location.href = BASE_URL + '/administrator/Settings_app/add';
         return false;
      });

      $('*').bind('keydown', 'Ctrl+f', function assets() {
         $('#sbtn').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+x', function assets() {
         $('#reset').trigger('click');
         return false;
      });

      $('*').bind('keydown', 'Ctrl+b', function assets() {

         $('#reset').trigger('click');
         return false;
      });
   }

   jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Settings App </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Settings App</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row">

      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->


               <form name="form_settings_app" id="form_settings_app" action="<?= base_url('administrator/settings_app/index'); ?>">

                  <!-- /.widget-user -->
                  <div class="row">

                     <div class="col-sm-6 col-md-2" style=""></div>
                     <div class="col-sm-12 col-md-10" style="float: right;">
                        <div class="col-sm-3 padd-left-0"></div>

                        <div class="col-sm-5 padd-left-0">
                           <input type="text" class="form-control" name="q" id="filter" placeholder="<?= 'Recherher'; ?>" value="<?= $this->input->get('q'); ?>">
                        </div>

                        <div class="col-sm-4">
                           <input type="hidden" name="f" id="field">
                           <div class="col-sm-2 padd-left-0 ">
                              <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                                 <i class="fa fa-search"></i>
                              </button>
                           </div>

                           <div class="col-sm-2 padd-left-0 ">
                              <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" title="Réinitialiser la recherche">
                                 <i class="fa fa-undo"></i>
                              </a>
                           </div>
                           <div class="col-sm-8">

                              <?php
                              $data_check = $this->db->get('settings_app');
                              if ($data_check->num_rows() != 1) { ?>
                                 <?php is_allowed('settings_app_add', function () { ?>
                                    <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['']); ?>  (Ctrl+a)" href="<?= site_url('administrator/settings_app/add'); ?>"><i class="fa fa-plus"></i> </a>
                                 <?php }) ?>

                              <?php } else {
                              } ?>

                              <?php is_allowed('settings_app_export', function () { ?>
                                 <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Settings App" href="<?= site_url('administrator/settings_app/export'); ?>"><i class="fa fa-file-excel-o"></i> </a>
                              <?php }) ?>
                              <?php is_allowed('settings_app_export', function () { ?>
                                 <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Settings App" href="<?= site_url('administrator/settings_app/export_pdf'); ?>"><i class="fa fa-file-pdf-o"></i> </a>
                              <?php }) ?>

                           </div>
                        </div>
                     </div>
                  </div>
                  <br>



                  <div class="table-responsive col-md-12">
                     <table class="table table-bordered table-striped dataTable">
                        <thead>
                           <tr class="">
                              <th>
                                 <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                              </th>
                              <th>Nom Entreprise</th>
                              <th>NIF</th>
                              <th>RC</th>
                              <th>TVA</th>
                              <th>Quartier</th>
                              <th>Avenue</th>
                              <th>Action</th>
                           </tr>
                        </thead>
                        <tbody id="tbody_settings_app">
                           <?php foreach ($settings_apps as $settings_app) : ?>
                              <tr>
                                 <td width="5">
                                    <input type="checkbox" class="flat-red check" name="id[]" value="<?= $settings_app->ID_SETTING; ?>">
                                 </td>

                                 <td><?= _ent($settings_app->NOM_ENTREPRISE); ?></td>
                                 <td><?= _ent($settings_app->NIF_ENTREPRISE); ?></td>
                                 <td><?= _ent($settings_app->RC_ENTREPRISE); ?></td>
                                 <td><?= $settings_app->TVA_ENTREPRISE == 0 ? 'TVA Inclus':'TVA Exclus'; ?></td>
                                 <td><?= _ent($settings_app->QUARTIER_ENTREPRISE); ?></td>
                                 <td><?= _ent($settings_app->AVENUE_ENTREPRISE); ?></td>
                                 <td width="200">
                                    <?php is_allowed('settings_app_view', function () use ($settings_app) { ?>
                                       <a style="margin-right: 2px" href="<?= site_url('administrator/settings_app/view/' . $settings_app->ID_SETTING); ?>" class="btn btn-warning btn-xs"><i class="fa fa-eye-slash"></i></a>
                                    <?php }) ?>
                                    <?php is_allowed('settings_app_update', function () use ($settings_app) { ?>
                                       <a href="<?= site_url('administrator/settings_app/edit/' . $settings_app->ID_SETTING); ?>" class="btn btn-info btn-xs"><i class="fa fa-pencil "></i> </a>
                                    <?php }) ?>
                                    <?php is_allowed('settings_app_delete', function () use ($settings_app) { ?>
                                       <a href="javascript:void(0);" data-href="<?= site_url('administrator/settings_app/delete/' . $settings_app->ID_SETTING); ?>" class="btn btn-danger btn-xs  remove-data"><i class="fa fa-close"></i></a>
                                    <?php }) ?>
                                 </td>
                              </tr>
                           <?php endforeach; ?>
                           <?php if ($settings_app_counts == 0) : ?>
                              <tr>
                                 <td colspan="100">
                                    Settings App data is not available
                                 </td>
                              </tr>
                           <?php endif; ?>
                        </tbody>
                     </table>
                  </div>
            </div>
            <hr>

            </form>
            <div class="row">
               <div class="col-md-4" style="float:right">
                  <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate">
                     <?= $pagination; ?>
                  </div>
               </div>
            </div>

         </div>
         <!--/box body -->
      </div>
      <!--/box -->
   </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
   $(document).ready(function() {

      $('.remove-data').click(function() {

         var url = $(this).attr('data-href');

         swal({
               title: "<?= cclang('are_you_sure'); ?>",
               text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
               type: "input",
               showCancelButton: true,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
               cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
               closeOnConfirm: true,
               closeOnCancel: true,
               animation: "slide-from-top",
               inputPlaceholder: "Donnez un commentaire S.V.P."
            },
            function(inputValue) {
               if (inputValue === false) {
                  return false;
               }
               if (inputValue === "") {
                  swal.showInputError("Vous devriez ecrire un commentaire SVP.!!!");
                  return false;
               }
               document.location.href = url + '?inputValue=' + inputValue;
            },
            function(isConfirm) {
               // if (isConfirm) {
               //    document.location.href = BASE_URL + '/administrator/settings_app/delete?' + serialize_bulk;      
               // }
            });

         return false;
      });


      $('#apply').click(function() {

         var bulk = $('#bulk');
         var serialize_bulk = $('#form_settings_app').serialize();

         if (bulk.val() == 'delete') {
            swal({
                  title: "<?= cclang('are_you_sure'); ?>",
                  text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
                  type: "input",
                  showCancelButton: true,
                  confirmButtonColor: "#DD6B55",
                  confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
                  cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
                  closeOnConfirm: true,
                  closeOnCancel: true,
                  animation: "slide-from-top",
                  inputPlaceholder: "Donnez un commentaire S.V.P."
               },
               function(inputValue) {
                  if (inputValue === false) {
                     return false;
                  }
                  if (inputValue === "") {
                     swal.showInputError("Vous devriez ecrire un commentaire SVP.!!!");
                     return false;
                  }
                  document.location.href = url + '?inputValue=' + inputValue;
               },
               function(isConfirm) {
                  // if (isConfirm) {
                  //    document.location.href = BASE_URL + '/administrator/settings_app/delete?' + serialize_bulk;      
                  // }
               });

            return false;

         } else if (bulk.val() == '') {
            swal({
               title: "Upss",
               text: "<?= cclang('please_choose_bulk_action_first'); ?>",
               type: "warning",
               showCancelButton: false,
               confirmButtonColor: "#DD6B55",
               confirmButtonText: "Okay!",
               closeOnConfirm: true,
               closeOnCancel: true
            });

            return false;
         }

         return false;

      }); /*end appliy click*/


      //check all
      var checkAll = $('#check_all');
      var checkboxes = $('input.check');

      checkAll.on('ifChecked ifUnchecked', function(event) {
         if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
         } else {
            checkboxes.iCheck('uncheck');
         }
      });

      checkboxes.on('ifChanged', function(event) {
         if (checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
         } else {
            checkAll.removeProp('checked');
         }
         checkAll.iCheck('update');
      });

   }); /*end doc ready*/
</script>