
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Pos_store_2_ibi_articles/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Articles<small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Articles</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('pos_store_2_ibi_articles_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Pos Store 2 Ibi Articles']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/pos_store_2_ibi_articles/add'); ?>"><i class="fa fa-plus-square-o" ></i> <?= cclang('add_new_button', ['Pos Store 2 Ibi Articles']); ?></a>
                        <?php }) ?>
                        <?php is_allowed('pos_store_2_ibi_articles_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> Pos Store 2 Ibi Articles" href="<?= site_url('administrator/pos_store_2_ibi_articles/export'); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
                        <?php is_allowed('pos_store_2_ibi_articles_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> pdf Pos Store 2 Ibi Articles" href="<?= site_url('administrator/pos_store_2_ibi_articles/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export'); ?> PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Articles</h3>
                     <h5 class="widget-user-desc"><?= cclang('list_all', ['Articles']); ?>  <i class="label bg-yellow"><?= $pos_store_2_ibi_articles_counts; ?>  <?= cclang('items'); ?></i></h5>
                  </div>

                  <form name="form_pos_store_2_ibi_articles" id="form_pos_store_2_ibi_articles" action="<?= base_url('administrator/pos_store_2_ibi_articles/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Nom Du Produit</th>
                           
                           <th>Categorie</th>
                           <th>Sous Categorie</th>
                           <th>Part No</th>
            
                           <th>Prix De Vente</th>
                           
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_pos_store_2_ibi_articles">
                     <?php foreach($pos_store_2_ibi_articless as $pos_store_2_ibi_articles): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $pos_store_2_ibi_articles->ID_ARTICLE; ?>">
                           </td>
                           
                           <td><?= _ent($pos_store_2_ibi_articles->DESIGN_ARTICLE); ?></td> 
                           
                             
                           <td>
                              <?php 
                                $user = $this->model_pos_ibi_fournisseurs->get_user_info('pos_ibi_categories',$pos_store_2_ibi_articles->ID_CATEGORIE,'ID_CATEGORIE');
                              if($user>0)
                                {

                                  foreach ($user as $value) 
                                    {
                                    
                                      echo "".$value->NOM_CATEGORIE;
                                    
                                    }
                                }
                             ?>
                           </td>
                             
                           <td>
                             <?php 
                                $user = $this->model_pos_ibi_fournisseurs->get_user_info('pos_ibi_categories',$pos_store_2_ibi_articles->REF_SOUS_CATEGORIE_ARTICLE,'ID_CATEGORIE');
                              if($user>0)
                                {

                                  foreach ($user as $value) 
                                    {
                                    
                                      echo "".$value->NOM_CATEGORIE;
                                    
                                    }
                                }
                             ?>
                             
                           </td> 
                           <td><?= _ent($pos_store_2_ibi_articles->SKU_ARTICLE); ?></td> 
                           
                           <td><?= _ent($pos_store_2_ibi_articles->PRIX_DE_VENTE_ARTICLE); ?></td> 
                          <!--  <td><?= _ent($pos_store_2_ibi_articles->SHADOW_PRICE_ARTICLE); ?></td> 
                           <td><?= _ent($pos_store_2_ibi_articles->PRIX_PROMOTIONEL_ARTICLE); ?></td> 
                           <td><?= _ent($pos_store_2_ibi_articles->SPECIAL_PRICE_START_DATE_ARTICLE); ?></td> 
                           <td><?= _ent($pos_store_2_ibi_articles->SPECIAL_PRICE_END_DATE_ARTICLE); ?></td> 
                           <td><?= _ent($pos_store_2_ibi_articles->TAILLE_ARTICLE); ?></td> 
                           <td><?= _ent($pos_store_2_ibi_articles->POIDS_ARTICLE); ?></td> 
                           <td><?= _ent($pos_store_2_ibi_articles->COULEUR_ARTICLE); ?></td> 
                           <td><?= _ent($pos_store_2_ibi_articles->HAUTEUR_ARTICLE); ?></td> 
                           <td><?= _ent($pos_store_2_ibi_articles->LARGEUR_ARTICLE); ?></td> 
                           <td><?= _ent($pos_store_2_ibi_articles->DESCRIPTION_ARTICLE); ?></td> 
                           <td>
                              <?php if (!empty($pos_store_2_ibi_articles->APERCU_ARTICLE)): ?>
                                <?php if (is_image($pos_store_2_ibi_articles->APERCU_ARTICLE)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/pos_store_2_ibi_articles/' . $pos_store_2_ibi_articles->APERCU_ARTICLE; ?>">
                                  <img src="<?= BASE_URL . 'uploads/pos_store_2_ibi_articles/' . $pos_store_2_ibi_articles->APERCU_ARTICLE; ?>" class="image-responsive" alt="image pos_store_2_ibi_articles" title="APERCU_ARTICLE pos_store_2_ibi_articles" width="40px">
                                </a>
                                <?php else: ?>
                                  <a href="<?= BASE_URL . 'administrator/file/download/pos_store_2_ibi_articles/' . $pos_store_2_ibi_articles->APERCU_ARTICLE; ?>">
                                   <img src="<?= get_icon_file($pos_store_2_ibi_articles->APERCU_ARTICLE); ?>" class="image-responsive image-icon" alt="image pos_store_2_ibi_articles" title="APERCU_ARTICLE <?= $pos_store_2_ibi_articles->APERCU_ARTICLE; ?>" width="40px"> 
                                 </a>
                                <?php endif; ?>
                              <?php endif; ?>
                           </td>
                            
                           <td><?= _ent($pos_store_2_ibi_articles->AUTHOR_ARTICLE); ?></td>  -->
                           <td width="200">
                              <?php is_allowed('pos_store_2_ibi_articles_view', function() use ($pos_store_2_ibi_articles){?>
                              <a href="<?= site_url('administrator/pos_store_2_ibi_articles/view/' . $pos_store_2_ibi_articles->ID_ARTICLE); ?>" class="btn btn-warning btn-sm"><span  class="glyphicon glyphicon-eye-open"></span></a>
                              <?php }) ?>
                              <?php is_allowed('pos_store_2_ibi_articles_update', function() use ($pos_store_2_ibi_articles){?>
                              <a href="<?= site_url('administrator/pos_store_2_ibi_articles/edit/' . $pos_store_2_ibi_articles->ID_ARTICLE); ?>" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-edit"></span></a>
                              <?php }) ?>
                              <?php is_allowed('pos_store_2_ibi_articles_delete', function() use ($pos_store_2_ibi_articles){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/pos_store_2_ibi_articles/delete/' . $pos_store_2_ibi_articles->ID_ARTICLE); ?>" class="btn btn-danger btn-sm remove-data"><span class="glyphicon glyphicon-remove"></span></a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($pos_store_2_ibi_articles_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Articles data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value=""><?= cclang('all'); ?></option>
                            <option <?= $this->input->get('f') == 'DESIGN_ARTICLE' ? 'selected' :''; ?> value="DESIGN_ARTICLE">DESIGN ARTICLE</option>
                           <option <?= $this->input->get('f') == 'REF_RAYON_ARTICLE' ? 'selected' :''; ?> value="REF_RAYON_ARTICLE">REF RAYON ARTICLE</option>
                           <option <?= $this->input->get('f') == 'REF_CATEGORIE_ARTICLE' ? 'selected' :''; ?> value="REF_CATEGORIE_ARTICLE">REF CATEGORIE ARTICLE</option>
                           <option <?= $this->input->get('f') == 'REF_SOUS_CATEGORIE_ARTICLE' ? 'selected' :''; ?> value="REF_SOUS_CATEGORIE_ARTICLE">REF SOUS CATEGORIE ARTICLE</option>
                           <option <?= $this->input->get('f') == 'SKU_ARTICLE' ? 'selected' :''; ?> value="SKU_ARTICLE">SKU ARTICLE</option>
                           <option <?= $this->input->get('f') == 'TYPE_ARTICLE' ? 'selected' :''; ?> value="TYPE_ARTICLE">TYPE ARTICLE</option>
                           <option <?= $this->input->get('f') == 'STATUS_ARTICLE' ? 'selected' :''; ?> value="STATUS_ARTICLE">STATUS ARTICLE</option>
                           <option <?= $this->input->get('f') == 'STOCK_ENABLED_ARTICLE' ? 'selected' :''; ?> value="STOCK_ENABLED_ARTICLE">STOCK ENABLED ARTICLE</option>
                           <option <?= $this->input->get('f') == 'PRIX_DE_VENTE_ARTICLE' ? 'selected' :''; ?> value="PRIX_DE_VENTE_ARTICLE">PRIX DE VENTE ARTICLE</option>
                           <option <?= $this->input->get('f') == 'SHADOW_PRICE_ARTICLE' ? 'selected' :''; ?> value="SHADOW_PRICE_ARTICLE">SHADOW PRICE ARTICLE</option>
                           <option <?= $this->input->get('f') == 'PRIX_PROMOTIONEL_ARTICLE' ? 'selected' :''; ?> value="PRIX_PROMOTIONEL_ARTICLE">PRIX PROMOTIONEL ARTICLE</option>
                           <option <?= $this->input->get('f') == 'SPECIAL_PRICE_START_DATE_ARTICLE' ? 'selected' :''; ?> value="SPECIAL_PRICE_START_DATE_ARTICLE">SPECIAL PRICE START DATE ARTICLE</option>
                           <option <?= $this->input->get('f') == 'SPECIAL_PRICE_END_DATE_ARTICLE' ? 'selected' :''; ?> value="SPECIAL_PRICE_END_DATE_ARTICLE">SPECIAL PRICE END DATE ARTICLE</option>
                           <option <?= $this->input->get('f') == 'TAILLE_ARTICLE' ? 'selected' :''; ?> value="TAILLE_ARTICLE">TAILLE ARTICLE</option>
                           <option <?= $this->input->get('f') == 'POIDS_ARTICLE' ? 'selected' :''; ?> value="POIDS_ARTICLE">POIDS ARTICLE</option>
                           <option <?= $this->input->get('f') == 'COULEUR_ARTICLE' ? 'selected' :''; ?> value="COULEUR_ARTICLE">COULEUR ARTICLE</option>
                           <option <?= $this->input->get('f') == 'HAUTEUR_ARTICLE' ? 'selected' :''; ?> value="HAUTEUR_ARTICLE">HAUTEUR ARTICLE</option>
                           <option <?= $this->input->get('f') == 'LARGEUR_ARTICLE' ? 'selected' :''; ?> value="LARGEUR_ARTICLE">LARGEUR ARTICLE</option>
                           <option <?= $this->input->get('f') == 'DESCRIPTION_ARTICLE' ? 'selected' :''; ?> value="DESCRIPTION_ARTICLE">DESCRIPTION ARTICLE</option>
                           <option <?= $this->input->get('f') == 'APERCU_ARTICLE' ? 'selected' :''; ?> value="APERCU_ARTICLE">APERCU ARTICLE</option>
                           <option <?= $this->input->get('f') == 'AUTHOR_ARTICLE' ? 'selected' :''; ?> value="AUTHOR_ARTICLE">AUTHOR ARTICLE</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/pos_store_2_ibi_articles');?>" title="<?= cclang('reset_filter'); ?>">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_pos_store_2_ibi_articles').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/pos_store_2_ibi_articles/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>