
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Client Deposit      <small><?= cclang('detail', ['Client Deposit']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/client_deposit'); ?>">Client Deposit</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Client Deposit</h3>
                     <h5 class="widget-user-desc">Detail Client Deposit</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_client_deposit" id="form_client_deposit" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID DEPOSIT </label>

                        <div class="col-sm-8">
                           <?= _ent($client_deposit->ID_DEPOSIT); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PAID TYPE </label>

                        <div class="col-sm-8">
                           <?= _ent($client_deposit->PAID_TYPE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">AMOUNT </label>

                        <div class="col-sm-8">
                           <?= _ent($client_deposit->AMOUNT); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PAID DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($client_deposit->PAID_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CREATED BY </label>

                        <div class="col-sm-8">
                           <?= _ent($client_deposit->CREATED_BY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">BANK NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($client_deposit->BANK_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">INVOICE NUMBER </label>

                        <div class="col-sm-8">
                           <?= _ent($client_deposit->INVOICE_NUMBER); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('client_deposit_update', function() use ($client_deposit){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit client_deposit (Ctrl+e)" href="<?= site_url('administrator/client_deposit/edit/'.$client_deposit->ID_DEPOSIT); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Client Deposit']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/client_deposit/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Client Deposit']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
