<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
  //This page is a result of an autogenerated content made by running test.html with firefox.
  function domo() {

    // Binding keys
    $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
      return false;
    });

    $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
      return false;
    });

  }


  jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h3>
    Rapports commandes du Serv. <?php 
       $user = $this->db->query('SELECT full_name from aauth_users WHERE id = '.$this->uri->segment(4).' ')->row_array();
       echo $user['full_name'];
    ?> <small> </small>
  </h3>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class=""><a href="<?= site_url('administrator/articles'); ?>">Commande</a></li>
    <li class="active"><?= cclang('detail'); ?></li>
  </ol>
</section>
<!-- Main content -->
<section class="content">
  <div class="row">

    <div class="col-md-12">
      <div class="box box-warning">
        <div class="box-body ">

          <!-- Widget: user widget style 1 -->
          <div class="box box-widget widget-user-2">
            <!-- Add the bg color to the header using any of the bg-* classes -->


            <form class="form-horizontal" name="form_hospital_ibi_articles" id="form_hospital_ibi_articles" action="<?= base_url('administrator/rapports/commande_serveurs/' . $this->uri->segment(4) . ''); ?>">


              <div class="widget-user-header ">
                <div class="row pull-center">
                  <div class="col-md-12">
                    <div class="col-lg-3 col-md-3 col-sm-3">
                      <div class="input-group">
                        <span class="input-group-addon">Start</span>
                        <input type="text" class="form-control dateTimePickers" name="date_depart" value="<?= $date_depart ?>">
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4">
                      <div class="input-group">
                        <span class="input-group-addon">End</span>
                        <input type="text" class="form-control dateTimePickers" name="date_fin" value="<?= $date_fin ?>">
                      </div>
                    </div>


                    <div class="col-lg-3 col-md-3 col-sm-3">
                       <div class="input-group">
                          <select class="form-control" name="status_command">
                             <option value=""> Type de facture</option>
                             <option value="0"> En Attente</option>
                             <?php
                                   foreach ($type_de_facture as $key) { ?>
                              <option value="<?php echo $key->ID_TYPE_FACTURE?>"> <?php echo $key->DESIGNATION_TYPE_FACTURE?></option>
                             <?php } ?>


                          </select>
                       </div>

                    </div>
          
                    <div class="col-lg-2 col-md-2 col-sm-2">
                      <div class="btn-group btn-group-md">
                        <button type="submit" name="name" class="btn btn-default"><i class="fa fa-refresh"></i>
                        </button>
                        <button type="button" print-item=".content-wrapper" name="name" class="btn btn-default" onclick="printTable()">
                          <i class="fa fa-print"></i>
                        </button>
                        <button type="button" name="name" class="btn btn-default" onclick="tableToExcel('headerTable', 'W3C Example Table')">
                          <i class="export glyphicon glyphicon-export"></i>
                        </button>
                      </div>
                    </div>

                  </div>
                </div>

              </div>
            </form>
            <div class="table-responsive">

              <div class="box">
                <div class="box-header with-border">CMD</div>
                <div class="box-body no-padding">
                  <table class="table  table-striped table-bordered"  id="headerTable">
                    <thead>
                      <tr>  
                        <th  class="text-center" width="100">CodeBar CMD.</th>
                        <th class="text-center" width="100">CMD Creer</th>
                         <th class="text-center" width="100">Statut CMD</th>
                         <th class="text-center" width="135">Client</th>
                         <th class="text-center" width="140">Date CMD</th>
                         <th class="text-center" width="135">Paiement Creer</th>
                      </tr>
                    </thead>
                    <tbody>

                      <?php foreach($CMD as $command){ ?>
                        <tr>
                          <td> <?= _ent($command->CODE)?> </td>  
                              <td> <?= $this->db->query("SELECT * FROM aauth_users WHERE id = ".$command->CREATED_BY_pos_IBI_COMMANDES." ")->row_array()["full_name"]; ?> 
                         </td>
                          <td> <? $status = $command->COMMANDE_STATUS;
                                    if($status ==0){
                                      echo "<i class='label bg-yellow'>En attente..</i>";
                                    }
                                   else if($status ==1){
                                     echo "<i class='label bg-blue'> En Avance </i>";
                                   }
                                   else if($status ==2){
                                      echo "<i class='label bg-green'> Payer </i>";
                                   }
                                   else if($status ==10){
                                      echo "<i class='label bg-red'> En Credit </i>";

                                   }
                                   else if($status ==11){
                                      echo "<i class='label bg-aqua'> Complementaire  </i>";
                                   }
                                   else{
                                      echo "<i class='label bg-black'> undefined </i>";       
                                    }

                          ?></td> 
                          <td>
                            <?php $client = $this->db->query("SELECT * FROM pos_clients WHERE ID_CLIENT = '".$command->CLIENT_ID_COMMANDE."' ")->row_array();
                                 echo $client['NOM_CLIENT']." ".$client['PRENOM'];
                             ?>
                          </td>
                          <td> <?= $command->DATE_CREATION_pos_IBI_COMMANDES;?></td>
                          <td> <?php $creater_pay = $this->db->query("SELECT * FROM aauth_users USERS INNER JOIN pos_paiements PAIE ON PAIE.CREATED_BY_PAIEMENT = USERS.id WHERE PAIE.COMMANDE_ID = '".$command->ID_pos_IBI_COMMANDES."' ")->row_array();
                                     if(empty($creater_pay['full_name'])){ echo " <i class ='label bg-red'> pas de paie</i>";}else{echo "<b>".$creater_pay['full_name']."</b>";}
                           ?>
                          </td>
                      
                          <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th>DESIGNATON</th>
                            <th>CODEBAR</th>
                            <th>QTE</th>
                            <th>PRIX_ARTICLE</th>
                            <th>DATE_CREER</th>

                          </tr>
                             <?php 

                               $getCommandDetail = $this->model_r_proforma->getLists('pos_ibi_commandes_produits',array('REF_COMMAND_CODE'=>$command->CODE)); 
                               foreach ($getCommandDetail as $key) { ?>
                          <tr>
                             <td></td>
                             <td></td>
                             <td></td>
                             <td></td>
                             <td> <?= $key['NAME']; ?></td>
                             <td>  <?= $key['REF_PRODUCT_CODEBAR']?> </td>
                             <td><?= $key['QUANTITE']?></td>
                             <td> <?= $key['PRIX_TOTAL']?> </td>
                            <td> <?= $key['DATE_CREATION_pos_IBI_COMMANDES_PRODUITS']?> </td>
                          
                          </tr>
                           <?php    } ?>
                           <th colspan="4"> TOTAL CMD </th>
                           <td colspan="3"></td>
                           <th colspan=""> 
                                <?php $sommes = $this->db->query("SELECT SUM(PRIX_TOTAL) AS sommes_toto FROM  pos_ibi_commandes_produits WHERE REF_COMMAND_CODE = '".$command->CODE."' ")->row_array(); 
                                   echo $sommes['sommes_toto'];
                                ?>

                           </th>
                        </tr>
                     <?php  }?>                     
                    </tbody>

                  </table>
                </div>
              </div>
            </div>

          </div>
        </div>
        <!--/box body  A_Bas-->
      </div>
      <!--/box A_Bas-->
    </div>
  </div>
</section>
<!-- /.content -->
<script type="text/javascript">
  var tableToExcel = (function() {
    var uri = 'data:application/vnd.ms-excel;base64,',
      template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>',
      base64 = function(s) {
        return window.btoa(unescape(encodeURIComponent(s)))
      },
      format = function(s, c) {
        return s.replace(/{(\w+)}/g, function(m, p) {
          return c[p];
        })
      }
    return function(table, name) {
      if (!table.nodeType) table = document.getElementById(table)
      var ctx = {
        worksheet: name || 'Worksheet',
        table: table.innerHTML
      }
      window.location.href = uri + base64(format(template, ctx))
    }
  })()

  function printTable() {
    var divToPrint = document.getElementById("headerTable");
    newWin = window.open("");
    newWin.document.write(divToPrint.outerHTML);
    newWin.print();
    newWin.close();
  }
</script>
<!-- nturubika rothshild david -->

<script type="text/javascript">
    $(".dateTimePickers").datetimepicker({
        maxDate: new Date(),
        maxDateTime:new Date().getTime(),
        format: "Y-m-d H:i:s",
        autoclose: true,
        todayBtn: true,
        startDate: "Y-m-d H:i:s",
        step: 1
    });
</script>