
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript"> 
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/articles/add/<?=$this->uri->segment(4);?>';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Liste des articles
   </h1>
   <h5 class="widget-user-desc"><i class="label bg-yellow"><?= $articles_counts; ?>  <?= cclang('items'); ?></i></h5>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Produits</li>
   </ol>
</section>
<!-- Main content -->
<?php 
   $id_user = get_user_data('id');
   $user_group = $this->model_registers->getOne('aauth_user_to_group',array('user_id'=>$id_user));
   $group = $this->model_registers->getOne('aauth_groups',array('id'=>$user_group['group_id']));
?>
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                <form name="form_articles" id="form_articles" action="<?= base_url('administrator/articles/index/'.$this->uri->segment(4).''); ?>">
                  <div class="widget-user-header ">
                     <div class="row pull-center" style="margin-left:5%">
                        <div class="col-md-8">
                          <div class="col-sm-2 padd-left-0 " >
                            <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                               <option value="">Bulk</option>
                               <?php is_allowed('articles_delete', function(){?>
                               <option value="delete">Delete</option>
                               <?php }) ?>
                            </select>
                         </div>
                         <div class="col-sm-2 padd-left-0 ">
                            <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                         </div>
                         <div class="col-sm-3 padd-left-0  " >
                            <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                         </div>
                         <div class="col-sm-3 padd-left-0 " >
                            <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                              <option value=""><?= cclang('all'); ?></option>
                                <option <?= $this->input->get('f') == 'CODEBAR_ARTICLE' ? 'selected' :''; ?> value="CODEBAR_ARTICLE">Codebarre</option>
                                <option <?= $this->input->get('f') == 'DESIGN_ARTICLE' ? 'selected' :''; ?> value="DESIGN_ARTICLE">Nom article</option>
                                <option <?= $this->input->get('f') == 'REF_CATEGORIE_ARTICLE' ? 'selected' :''; ?> value="REF_CATEGORIE_ARTICLE">Nom de la famille</option>
                                <option <?= $this->input->get('f') == 'REF_SOUS_CATEGORIE_ARTICLE' ? 'selected' :''; ?> value="REF_SOUS_CATEGORIE_ARTICLE">Nom de la categorie</option>
                                <option <?= $this->input->get('f') == 'SKU_ARTICLE' ? 'selected' :''; ?> value="SKU_ARTICLE">Reference</option>
                                <?php if($group['name'] == 'Admin'){ ?>
                                    <option <?= $this->input->get('f') == 'INDISPONIBLE' ? 'selected' :''; ?> value="INDISPONIBLE">Indisponible</option>
                                 <?php } ?>
                              </select>
                         </div>
                         <div class="col-sm-1 padd-left-0 ">
                            <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                            Filter
                            </button>
                         </div>
                         <div class="col-sm-1 padd-left-0 ">
                            <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/articles/index/'.$this->uri->segment(4).'');?>" title="<?= cclang('reset_filter'); ?>">
                            <i class="fa fa-undo"></i>
                            </a>
                         </div>
                      </div>
                        <?php is_allowed('articles_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="Ajouter le produit" href="<?=  site_url('administrator/articles/add/'.$this->uri->segment(4).''); ?>"><i class="glyphicon glyphicon-plus" ></i> </a>
                        <?php }) ?>
                        <?php is_allowed('articles_export', function(){?>
                        <a class="btn btn-flat btn-success" title="Export XLS" href="<?= site_url('administrator/articles/export/'.$this->uri->segment(4).''); ?>"><i class="fa fa-file-excel-o" ></i> </a>
                        <?php }) ?>
                        <?php is_allowed('articles_reserve_list', function(){?>
                        <a class="btn btn-flat btn-success" title="Article Reserve" href="<?= site_url('administrator/articles/article_reserve/'.$this->uri->segment(4).''); ?>"><i class="fa fa-file-pdf-o" ></i> </a>
                        <?php }) ?>
                        <?php is_allowed('articles_import', function(){?>
                        <a class="btn btn-flat btn-success" title="Import XLSX" href="<?= site_url('administrator/articles/import/'.$this->uri->segment(4).''); ?>"><i class="glyphicon glyphicon-import" ></i></a>
                        <?php }) ?>
                     </div>
                  </div>
              </form>

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Codebarre</th>
                           <th>Nom du produit</th>
                           <?php if($this->uri->segment(4) == 1){?>
                           <th>Part No</th>
                           <th>Location</th>
                           <?php } ?>
                           <th>Famille</th>
                           <th>Catégorie</th>
                           <th>Restant</th>
                           <th>Reservées</th>
                           <?php is_allowed('articles_view_price', function(){?>
                           <th>Prix de vente</th>
                           <th>Mininum</th>
                           <?php
                           }) ?> 
                           <th>Apercu</th>
                           <?php if($group['name'] == 'Admin'){ ?>
                           <?php if($this->uri->segment(4) == 2){?>
                           <th>Part No</th>
                           <?php } ?>
                           <th>Prix d'achat</th>
                           <th>Ancien Prix</th>
                           <th>Author</th>
                           <?php } ?>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_articles">
                     <?php foreach($articless as $articles): 

                        $status_article = $articles->STATUS_ARTICLE;
                        if($status_article == 0) {
                           if($group['name'] == 'Admin'){
                              $see = '';
                              $style = 'style= "background-color: #F76161 !important"';
                           }else {
                              $see = 'hidden';
                              $style = '';
                           }
                        } else {
                           $see = '';$style = '';
                        }
                      ?>
                        <tr <?= $see ?> <?= $style ?>>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $articles->ID_ARTICLE; ?>">
                           </td>
                           <td>
                             
                           <?= _ent($articles->CODEBAR_ARTICLE); ?>
                           
                           </td>
                           
                           <td><?= _ent($articles->DESIGN_ARTICLE); ?></td> 
                           <?php if($this->uri->segment(4) == 1){?>
                           <td><?= _ent($articles->SKU_ARTICLE); ?></td>
                           <td><?php 
                                $rayon = $this->model_fournisseurs->get_user_info('pos_store_'.$this->uri->segment(4).'_ibi_rayons',$articles->REF_RAYON_ARTICLE,'ID_RAYON');
                              if($rayon>0)
                                {

                                  foreach ($rayon as $value) 
                                    {
                                    
                                      echo "".$value->TITRE_RAYON;
                                    
                                    }
                                }
                             ?>
                            </td>    
                           <?php } ?>
                           <td>
                              <?php 
                                $famille = $this->model_fournisseurs->get_user_info('pos_store_'.$this->uri->segment(4).'_famille',$articles->REF_CATEGORIE_ARTICLE,'ID_FAMILLE');
                              if($famille>0)
                                {

                                  foreach ($famille as $value) 
                                    {
                                    
                                      echo "".$value->NOM_FAMILLE;
                                    
                                    }
                                }
                             ?>
                           </td>
                             
                           <td>
                             <?php 
                                $categorie = $this->model_fournisseurs->get_user_info('pos_store_'.$this->uri->segment(4).'_ibi_categories',$articles->REF_SOUS_CATEGORIE_ARTICLE,'ID_CATEGORIE');
                              if($categorie>0)
                                {

                                  foreach ($categorie as $value) 
                                    {
                                    
                                      echo $value->NOM_CATEGORIE;
                                    
                                    }
                                }
                             ?>
                             
                           </td> 
                           
                           <td><?= _ent($articles->QUANTITE_RESTANTE_ARTICLE); ?></td>
                           <th><?= _ent($articles->RESERVE_ARTICLE); ?></th> 
                           <?php is_allowed('articles_view_price', function() use ($articles){?>
                           <td><?= _ent(strrev(wordwrap(strrev($articles->PRIX_DE_VENTE_ARTICLE), 3, ' ', true))); ?></td>
                           <td><?= _ent($articles->MINIMUM_QUANTITY_ARTICLE); ?></td>
                            <?php
                            }) ?> 
                           <td>
                              <?php if (!empty($articles->APERCU_ARTICLE)): ?>
                                <?php if (is_image($articles->APERCU_ARTICLE)): ?>
                                <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/articles/' . $articles->APERCU_ARTICLE; ?>">
                                  <img src="<?= BASE_URL . 'uploads/articles/' . $articles->APERCU_ARTICLE; ?>" class="image-responsive" alt="image articles" title="APERCU_ARTICLE articles" width="40px">
                                </a>
                                <?php else: ?>
                                  <a href="<?= BASE_URL . 'administrator/file/download/articles/' . $articles->APERCU_ARTICLE; ?>">
                                   <img src="<?= get_icon_file($articles->APERCU_ARTICLE); ?>" class="image-responsive image-icon" alt="image articles" title="APERCU_ARTICLE <?= $articles->APERCU_ARTICLE; ?>" width="40px"> 
                                 </a>
                                <?php endif; ?>
                              <?php endif; ?>
                           </td>
                           <?php if($group['name'] == 'Admin'){ ?>
                           <?php if($this->uri->segment(4) == 2){?>
                           <td><?= _ent($articles->SKU_ARTICLE); ?></td>
                           <?php } ?>
                           <td><?= _ent(strrev(wordwrap(strrev($articles->PRIX_DACHAT_ARTICLE), 3, ' ', true))); ?></td> 
                           <td><?= $articles->ANCIEN_PRIX ?></td>
                           <td><?= $articles->username; ?></td>
                           <?php } ?>
                           <td width="150">
                            <?php is_allowed('articles_delete', function() use ($articles){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/articles/delete/'.$this->uri->segment(4).'/' . $articles->ID_ARTICLE); ?>" class="btn btn-danger btn-xs remove-data"><span class="glyphicon glyphicon-remove"></span></a>
                               <?php }) ?>
                              <?php is_allowed('articles_update', function() use ($articles){?>
                              <a href="<?= site_url('administrator/articles/edit/'.$this->uri->segment(4).'/' . $articles->ID_ARTICLE); ?>" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-edit"></span></a>
                              <?php }) ?>
                               <?php is_allowed('articles_update', function() use ($articles){?>
                              <a href="<?= site_url('qr/?barcode='. $articles->CODEBAR_ARTICLE); ?>" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-barcode" title="Generate Codebarre"></span></a>
                              <?php }) ?>
                              <?php is_allowed('articles_view', function() use ($articles){?>
                              <a href="<?= site_url('administrator/articles/view/'.$this->uri->segment(4).'/' . $articles->ID_ARTICLE); ?>" class="btn btn-warning btn-xs"><span  class="glyphicon glyphicon-list" title="Historique"></span></a>
                              <?php }) ?>
                              <?php is_allowed('articles_view', function() use ($articles){?>
                              <a href="<?= site_url('administrator/articles/etiquete/'.$this->uri->segment(4).'/' . $articles->ID_ARTICLE); ?>" class="btn btn-default btn-xs"><span  class="glyphicon glyphicon-eye-open" title="Etiquete"></span></a>
                              <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($articles_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Les données sur les produits ne sont pas disponibles
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                  </div>                
                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_articles').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/articles/delete/<?=$this->uri->segment(4);?>?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>