<style>
   .chosen-container.chosen-container-single{
      width:100% !important;
   }
</style>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/pos_flux_caisse/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Flux Caisse   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Flux Caisse</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->


                  <form name="form_pos_flux_caisses" id="form_pos_flux_caisses" action="<?= base_url('administrator/pos_flux_caisse/index'); ?>">
                  
                      <!-- /.widget-user -->
                


                <div class="row" style="">
                   
                           
                           <div class="col-md-12 col-lg-12 col-sm-12">

                          

                           <div class="col-lg-3 col-md-3 col-sm-3">
                              <div class="input-group">
                                 <span class="input-group-addon"><b> Debut</b></span>
                                 <input type="date" class="form-control" name="date_start" value="">
                              </div>
                           </div>

                           <div class="col-lg-3 col-md-3 col-sm-3">
                              <div class="input-group">
                                 <span class="input-group-addon"><b> Fin </b></span>
                                 <input type="date" class="form-control" name="date_end" value="">
                              </div>
                           </div>
                        
                                                
                              <div class="col-sm-3 col-lg-3 col-md-3" >
                                 <input type="text" class="form-control" name="q" id="filter" placeholder="<?= 'Recherher'; ?>" value="<?= $this->input->get('q'); ?>">
                              </div> 
                              <input type="hidden" name="f" id="field"> 
                              <div class="col-sm-1 col-lg-1 col-md-1" >
                                 <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                                 <i class="fa fa-search"></i>
                                 </button>
                              </div>

                           <div class="col-sm-1 col-lg-1 col-md-1" >
 
                        <?php is_allowed('pos_flux_caisse_add', function(){?>
                        <?php $responser = $this->db->query("SELECT * FROM pos_session WHERE SESSION_STATUS =0")->num_rows();
                              if ($responser > 0) {?>
                                         
                           <button type="button" class="btn btn-primary" data-toggle="modal"
                              data-target=".bd-example-modal-md"><i class="fa fa-plus-circle"></i></button>


                           <?php } else{ ?>
                              <button type="button" class="btn btn-primary show_msg"><i class="fa fa-plus-circle"></i></button>
                           <?php } ?>
                        <?php }) ?>
                        
                       </div>
                   </div>
            </div>
               <hr>
                  <div class="table-responsive" id="lister"> 
                  <table class="table table-bordered table-striped dataTable table_flux" id="table_flux">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>Description</th>
                           <!-- <th>Nom Flux Caisse</th> -->
                           <th>Montant</th>
                           <th>Type Flux</th>
                           <th>Categorie Flux</th>
                           <th>Auteur</th>
                           <th>Date Creation</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_pos_flux_caisse">
                     <?php foreach($pos_flux_caisses as $pos_flux_caisse): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $pos_flux_caisse->ID_FLUX_CAISSE; ?>">
                           </td>
                           <td><?= _ent($pos_flux_caisse->DESCRIPTION_FLUX); ?></td> 
                           <!-- <td><?= _ent($pos_flux_caisse->NOM_FLUX_CAISSE); ?></td>  -->
                           <td><?= _ent($pos_flux_caisse->MONTANT_FLUX_CAISSE); ?></td> 
                           <td><?= _ent($pos_flux_caisse->DESIGN_ACTIVITE); ?></td>
                             
                           <td><?= _ent($pos_flux_caisse->NOM_CATEGORIE); ?></td>
                           <td><?= get_name_user($pos_flux_caisse->USER_CREATE_FLUX); ?></td> 
                           <td><?= _ent($pos_flux_caisse->DATE_CREATION_FLUX); ?></td> 
                           <td width="100">
                              <?php /*is_allowed('pos_flux_caisse_view', function() use ($pos_flux_caisse){?>
                              <a style="margin-right: 2px" href="<?= site_url('administrator/pos_flux_caisse/view/' . $pos_flux_caisse->ID_FLUX_CAISSE); ?>"  class="btn btn-warning btn-xs"><i class="fa fa-eye-slash"></i></a>
                              <?php })*/ ?>
                              <?php is_allowed('pos_flux_caisse_update', function() use ($pos_flux_caisse){?>

                                 <a type="button" title="modification" onclick="get_flux_caisse(this)"
                                    id="<?php echo $pos_flux_caisse->ID_FLUX_CAISSE; ?>"
                                    class="btn btn-info btn-xs" data-toggle="modal"
                                    data-target="#bd-example-modal-lgUp"> <i class="fa fa-pencil-square-o"
                                       aria-hidden="true"></i> </a>
                             
                              <?php }) ?>
                              <?php is_allowed('pos_flux_caisse_delete', function() use ($pos_flux_caisse){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/pos_flux_caisse/delete/' . $pos_flux_caisse->ID_FLUX_CAISSE); ?>" class="btn btn-danger btn-xs  remove-data"><i class="fa fa-close"></i></a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($pos_flux_caisse_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Flux Caisse data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
           
               </form>                  
                  <div class="row">
                  <div class="col-md-4" style="float:right">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>

            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>


   <div class="modal fade bd-example-modal-lgUp" id="bd-example-modal-lgUp" tabindex="-1" role="dialog"
               aria-labelledby="myLargeModalLabel" aria-hidden="true">
               <div class="modal-dialog modal-md">
                  <div class="modal-content">
                     <div class="modal-header">
                        <h4 class="modal-title" id="exampleModalLabel">Modification </h4>
                     </div>


                     <div class="modal-body">
                        <?= form_open(base_url('administrator/pos_flux_caisse /edit_save/'.$this->uri->segment(4)), [
                                              'name'    => 'form_pos_flux_up',
                                              'class'   => 'form-horizontal',
                                              'id'      => 'form_pos_flux_up',
                                              'method'  => 'POST'
                                              ]); ?>

                        <div class="row">

                           <div class="col-md-12">
                      
                 <div class="form-group ">
                           <label for="TYPE_ACTIVITE"
                              class="col-sm-12"> Type
                              <i class="required">*</i>
                           </label>
                           <div class="col-sm-12">
                            <select class="form-control chosen  chosen-select-deselect" name="TYPE_ACTIVITE_UP"
                                    id="TYPE_ACTIVITE_UP">
                                    <option value="">Selection de l'activité</option>
                                    <?php $type_activite=$this->db->get_where('  pos_activite_flux_caisse',['DELETE_STATUS'=>0] )->result();
                                     foreach ($type_activite as $itms) { ?>
                                    <option value="<?php echo $itms->ID_ACTIVITE?>"><?php echo $itms->DESIGN_ACTIVITE?></option>
                                        
                                    <?php } ?>


                                 </select>
                           </div>
                        </div>

                        <div class="form-group" id="cat_flux">
                              <label for="CATEGORIE_FLUX"
                                 class="col-sm-8">Categorie
                                 <i class="required">*</i>
                              </label>
                              <div class="col-sm-12">
                                 <select class="form-control chosen  chosen-select-deselect" name="CATEGORIE_FLUX_UP"
                                    id="CATEGORIE_FLUX_UP">
                                    <option value="">Selection de categorie</option>
                                    <?php $select_cat = $this->db->query("SELECT * FROM pos_categorie_flux_caisse WHERE DELETE_STATUS_CATEGORIE = 0")->result();
                               foreach ($select_cat as $categorie) {  ?>
                                    <option
                                       value="<?= $categorie->ID_CATEGORIE; ?>">
                                       <?php echo $categorie->NOM_CATEGORIE; ?>
                                    </option>
                                    <?php } ?>
                                 </select>
                              </div>
                           </div>
                        

                        <div class="form-group ">
                               <label for="MONTANT_FLUX_CAISSE"
                                 class="col-sm-8">Montant
                                 <i class="required">*</i>
                              </label>
                              <div class="col-sm-12">
                                 <input type="hidden" name="ID_FLUX_CAISSE_UP" id="ID_FLUX_CAISSE_UP" value="">
                                 <input type="number" class="form-control"
                                    name="MONTANT_FLUX_CAISSE_UP" id="MONTANT_FLUX_CAISSE_UP"
                                    placeholder="Montant de l'activité"
                                    value="">

                              </div>
                           </div>


                        
                           

                
                                      <div class="form-group ">
                              <label for="DESCRIPTION_FLUX"
                                 class="col-sm-8">Description<i
                                    class="required">*</i>
                              </label>
                              <div class="col-sm-12">
                                  <textarea type="text" class="form-control" name="DESCRIPTION_FLUX_UP"
                                       id="DESCRIPTION_FLUX_UP" placeholder="Description"
                                       value=""></textarea>

                              </div>
                           </div>
                        
                     </div>
                        </div>





                        <?= form_close(); ?>


                     </div>

                     <div class="modal-footer">
                        <button type="button" class="btn btn-danger btn_quit_up" data-dismiss="modal">Retour</button>
                        <button type="button" class="btn btn-primary btn_save_up btn_action" id="btn_save"
                           data-stype='back'>Modifier</button>

                        <br><br>
                        <div class="message text-left"></div>
                        <span class="loading loading-hide">
                           <img
                              src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg">
                           <i><?= cclang('loading_saving_data'); ?></i>
                     </div>


                  </div>
               </div>


            </div>





   <div class="modal fade bd-example-modal-md" tabindex="-1" id="nouveau flux"
         role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
         <div class="modal-dialog modal-md">
            <div class="modal-content">

               <div class="modal-header">
                  <h4 class="modal-title text-center" id="exampleModalLabel">Activité caisse
                  </h4>
               </div>
               <div class="modal-body">


            <?= form_open('', [
                 'name'    => 'form_pos_flux_caisse',
                 'class'   => 'form-horizontal',
                 'id'      => 'form_pos_flux_caisse',
                 'enctype' => 'multipart/form-data',
                 'method'  => 'POST'
               ]); ?>

                     <div class="row">

                   <div class="col-md-12">
                      
                 <div class="form-group ">
                           <label for="TYPE_ACTIVITE"
                              class="col-sm-12"> Type
                              <i class="required">*</i>
                           </label>
                           <div class="col-sm-12">
                            <select class="form-control chosen  chosen-select-deselect" name="TYPE_ACTIVITE"
                                 id="TYPE_ACTIVITE">
                                 <option value="">Selection de l'activité</option>
                                 <?php $type_activite=$this->db->get_where('pos_activite_flux_caisse',['DELETE_STATUS'=>0] )->result();
                                  foreach ($type_activite as $itms) { ?>
                                 <option value="<?php echo $itms->ID_ACTIVITE?>"><?php echo $itms->DESIGN_ACTIVITE ?></option>
                                     
                                 <?php }
                                 ?>


                              </select>
                           </div>
                        </div>

                        <div class="form-group" id="cat_flux">
                              <label for="CATEGORIE_FLUX"
                                 class="col-sm-8">Categorie
                                 <i class="required">*</i>
                              </label>
                              <div class="col-sm-12">
                                 <select class="form-control chosen  chosen-select-deselect" name="CATEGORIE_FLUX"
                                    id="CATEGORIE_FLUX">
                                    <option value="">Selection de categorie</option>
                                    <?php $select_cat = $this->db->query("SELECT * FROM pos_categorie_flux_caisse WHERE DELETE_STATUS_CATEGORIE = 0")->result();
                               foreach ($select_cat as $categorie) {  ?>
                                    <option
                                       value="<?= $categorie->ID_CATEGORIE; ?>">
                                       <?php echo $categorie->NOM_CATEGORIE; ?>
                                    </option>
                                    <?php } ?>
                                 </select>
                              </div>
                           </div>
                        

                        <div class="form-group ">
                               <label for="MONTANT_FLUX_CAISSE"
                                 class="col-sm-8">Montant
                                 <i class="required">*</i>
                              </label>
                              <div class="col-sm-12">
                                 <input type="number" class="form-control"
                                    name="MONTANT_FLUX_CAISSE" id="MONTANT_FLUX_CAISSE"
                                    placeholder="Montant de l'activité"
                                    value="<?= set_value('MONTANT_FLUX_CAISSE'); ?>">

                              </div>
                           </div>


                        
                           

                
                                      <div class="form-group ">
                              <label for="DESCRIPTION_FLUX"
                                 class="col-sm-8">Description<i
                                    class="required">*</i>
                              </label>
                              <div class="col-sm-12">
                                 <textarea type="text" class="form-control"
                                    name="DESCRIPTION_FLUX" id="DESCRIPTION_FLUX"
                                    placeholder="Description Depense"
                                    value="<?= set_value('DESCRIPTION_FLUX'); ?>"></textarea>

                              </div>
                           </div>
                        
                     </div>


                     <br>
                     <div class="message"></div>
                     <div class="row-fluid col-md-7">

                        <span class="loading loading-hide">
                           <img
                              src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg">
                           <i><?= cclang('loading_saving_data'); ?></i>
                        </span>
                     </div>
                    

                  </div>
                  <div class="modal-footer">
                     <button type="button" class="btn btn-danger btn_quit"
                        data-dismiss="modal">Retour</button>
                     <button type="button" class="btn btn-primary btn_save btn_action"
                        id="btn_save" data-stype='back'>Enregistrer</button>
                  </div>
               <?= form_close(); ?>

               </div>
            </div>
         </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){

      $('.show_msg').click(function(){

      sweetAlert('Vous devriez ouvrir une session caisse');

      return false;
    });
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "input",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
          closeOnConfirm: true,
          closeOnCancel: true,
          animation:"slide-from-top",
          inputPlaceholder: "Donnez un commentaire S.V.P."
        },
        function(inputValue){
            if (inputValue === false) {
               return false;
            }
            if (inputValue === "") {
               swal.showInputError("Vous devriez ecrire un commentaire SVP.!!!");
               return false;
            }
            document.location.href = url +'?inputValue=' +inputValue;
          },
          function(isConfirm){
            // if (isConfirm) {
            //    document.location.href = BASE_URL + '/administrator/pos_flux_caisse/delete?' + serialize_bulk;      
            // }
          });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_pos_flux_caisses').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "input",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",
            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",
            closeOnConfirm: true,
            closeOnCancel: true,
            animation:"slide-from-top",
            inputPlaceholder: "Donnez un commentaire S.V.P."
          },
          function(inputValue){
            if (inputValue === false) {
               return false;
            }
            if (inputValue === "") {
               swal.showInputError("Vous devriez ecrire un commentaire SVP.!!!");
               return false;
            }
            document.location.href = url +'?inputValue=' +inputValue;
          },
          function(isConfirm){
            // if (isConfirm) {
            //    document.location.href = BASE_URL + '/administrator/pos_flux_caisse/delete?' + serialize_bulk;      
            // }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/


  $('.btn_quit').click(function() {
      $('#CATEGORIE_DEPENSE').val("");
      $('#DESCRIPTION_DEPENSE').val("");
      $('#DESCRIPTION_DEPENSE').val("");
      $('#MONTANT_DEPENSE').val();
      $('#TYPE_ACTIVITE').val("");
      $('NOM_DEPENSE');
   })


   $('.btn_save').click(function() {
      $('.message').fadeOut();

      var form_pos_flux_caisse = $('#form_pos_flux_caisse');
      var data_post = form_pos_flux_caisse.serializeArray();
      var save_type = $(this).attr('data-stype');

      data_post.push({
         name: 'save_type',
         value: save_type
      });
      $('.loading').show();

      $.ajax({
            url: BASE_URL + '/administrator/pos_flux_caisse/add_save',
            type: 'POST',
            dataType: 'json',
            data: data_post,
         })
         .done(function(res) {
            if (res.success) {

               $('#table_flux').load(' #table_flux');
               $('#nouveau flux').modal('hide');
               $('.message').css('display', 'none');

               toastr['success']('Flux caisse ajouter!!');
               $('#TYPE_ACTIVITE').val('');
               // $('.message').fadeOut();



               if (save_type == 'back') {
                  window.location.href = res.redirect;
                  return;
               }

               // $('.message').printMessage({
               //   message: res.message
               // });
               // $('.message').fadeIn();
               resetForm();
               $('.chosen option').prop('selected', false).trigger('chosen:updated');

            } else {
               $('.message').printMessage({
                  message: res.message,
                  type: 'warning'
               });
            }

         })
         .fail(function() {
            $('.message').printMessage({
               message: 'Error save data',
               type: 'warning'
            });
         })
         .always(function() {
            $('.loading').hide();
            $('html, body').animate({
               scrollTop: $(document).height()
            }, 2000);
         });

      return false;
   }); /*end btn save*/

   function get_flux_caisse(th) {
      let id = $(th).attr('id');

      //alert(id);return;

      $.ajax({
         url: BASE_URL + '/administrator/pos_flux_caisse/get_flux_caisse',
         type: 'POST',
         dataType: 'json',
         data: {
            id: id
         },
         success: function(dt) {
            console.log(dt);
            $("#TYPE_ACTIVITE_UP").val(dt.TYPE_FLUX_CAISSE);
            $("#CATEGORIE_FLUX_UP").val(dt.CATEGORIE_FLUX);
            $("#MONTANT_FLUX_CAISSE_UP").val(dt.MONTANT_FLUX_CAISSE);
            $("#DESCRIPTION_FLUX_UP").val(dt.DESCRIPTION_FLUX);
            $('#ID_FLUX_CAISSE_UP').val(dt.ID_FLUX_CAISSE);


         }
      })

   }

   $('.btn_save_up').click(function() {
      $('.message').fadeOut();

      var form_pos_flux_up = $('#form_pos_flux_up');
      var data_post = form_pos_flux_up.serializeArray();
      var save_type = $(this).attr('data-stype');
      let id = $('#ID_FLUX_CAISSE_UP').val();
      // alert(id);return false;

      data_post.push({
         name: 'save_type',
         value: save_type
      });
      $('.loading').show();

      $.ajax({
            url: BASE_URL + '/administrator/pos_flux_caisse/edit_save/' + id,
            type: 'POST',
            dataType: 'json',
            data: data_post,
         })
         .done(function(res) {
            if (res.success) {

               $('#table_flux').load(' #table_flux');
               $('#bd-example-modal-lgUp').modal('hide');
               $('.message').css('display', 'none');

              toastr['success']('Modification Faite...');

               // $('.message').fadeOut();



               if (save_type == 'back') {
                  window.location.href = res.redirect;
                  return;
               }


               resetForm();
               $('.chosen option').prop('selected', false).trigger('chosen:updated');

            } else {
               $('.message').printMessage({
                  message: res.message,
                  type: 'warning'
               });
            }

         })
         .fail(function() {
            $('.message').printMessage({
               message: 'Error save data',
               type: 'warning'
            });
         })
         .always(function() {
            $('.loading').hide();
            $('html, body').animate({
               scrollTop: $(document).height()
            }, 2000);
         });

      return false;
   }); /*end btn save*/

</script>
