
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Session      <small><?= cclang('detail', ['Session']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/pos_session'); ?>">Session</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">

                  <div class="form-horizontal" name="form_pos_session" id="form_pos_session" >
                
                                         
                    <div id="dossier">
                        <div class="col-md-12 hidden-print">
                            <button type="button" class="btn btn-flat btn-info pull-right" onclick="window.print()"><i class="fa fa-print"></i></button>
                        </div>

                        <h4>Detaille de la session du <?=$date->SESSION_START ?> au <?=$date->SESSION_END ?></h4>
                            <table class="table-responsive table  table-striped" id="headerTable">

                                <tbody>
                                       
                                       <?php $tot_g=0;$var_sortie='';$var_entree=''; for ($i=0; $i < count($res) ; $i++) { 

                                            if ($res[$i]['type_name']=="Sorties"){


                                        

                                         
                                       

                                       $var_sortie = ' <tr colspan="3" style="background-color: #ccc !important;">
                                            <td style="text-transform: uppercase"><b>'.$res[$i]['type_name'].'
                                            </b>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            
                                         
                                        </tr>
                                        <tr>
                                            
                                            <th >DESIGNATION</th>
                                            <th colspan="1" class="text-left">CATEGORIE</th>
                                            <th colspan="1" class="text-center">MONTANT </th>
                                            <th colspan="1" class="text-center">TOTAL</th>
                                        </tr>
                                        <!-- <tr>

                                            <td class="" width="" colspan="100">
                                                <b>Désignation</b>
                                            </td>
                                           
                                      
                                        </tr> -->';
                                            
                                            }
                                        
                                    if($res[$i]['type_name']=="paiement" || $res[$i]['type_name']=="Entrées"){
                                        $var_entree = '<tr colspan="3" style="background-color: #ccc !important;">
                                            <td style="text-transform: uppercase"><b>Entrées et Paiement
                                            </b>
                                            </td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            
                                         
                                        </tr>
                                        <tr>
                                            
                                            <th >DESIGNATION</th>
                                            <th colspan="1" class="text-left">CATEGORIE</th>
                                            <th colspan="1" class="text-center">MONTANT </th>
                                            <th colspan="1" class="text-center">TOTAL</th>
                                        </tr>';
                                    } }
                                            
                                             $tot_sortie=0; $tot_entree=0; foreach($res as $k=>$v):   ;
                                                if ($v['type_name']=="Sorties") {
                                                 
                                                
                                                $var_sortie.='<tr style="background-color: ;" >

                                                    <td style="background-color: ;" class="text-left">
                                                     '.$v['categorie'].'
                                                    </td>

                                                    <td style="background-color: ;">
                                                        
                                                            '.$v['descript'].'

                                                         
                                                    </td>

                                                    <td style="background-color: ;">

                                                       <center>
                                                            '.$v['montant'].'
                                                        </center>

                                                    </td>
                                                    <td style="background-color: ;">
                                                        <center>
                                                          '.$v['montant'].'
                                                        </center>
                                                    </td>
                                                    

                                                </tr>';
                                                $tot_sortie+=$v['montant'];

                                                }
                                                elseif($v['type_name']=="paiement" || $v['type_name']=="Entrées"){

                                                    $var_entree.='<tr style="background-color: ;" >

                                                    <td style="background-color: ;" class="text-left">
                                                     '.$v['categorie'].'
                                                    </td>

                                                    <td style="background-color: ;">
                                                        
                                                            '.$v['descript'].'

                                                         
                                                    </td>

                                                    <td style="background-color: ;">

                                                       <center>
                                                            '.$v['montant'].'
                                                        </center>

                                                    </td>
                                                    <td style="background-color: ;">
                                                        <center>
                                                          '.$v['montant'].'
                                                        </center>
                                                    </td>
                                                    

                                                </tr>';
                                                $tot_entree+=$v['montant'];

                                             } endforeach; $tot_g=$tot_entree+$tot_sortie;
                                            echo $var_sortie.'

                                         <tr>
                                            <td class="" width="" colspan="3">
                                                TOTAL 
                                            </td>
                                        


                                        
                                            <td style="font-weight: bold;">
                                                <center>
                                                   '.$tot_sortie.'
                                                </center>
                                            </td>
                                            
                                        </tr>
                                             '.$var_entree;

                                              ?>
                                            <tr>
                                            <td class="" width="" colspan="3">
                                                TOTAL 
                                            </td>
                                        


                                        
                                            <td style="font-weight: bold;">
                                                <center>
                                                   <?=$tot_entree;?>
                                                </center>
                                            </td>
                                            
                                        </tr>


                                </tbody>

                                <tfoot >
                                    <tr style="background-color: #a5b2b0 !important;"> 
                                        <th colspan="3"> TOTAL GENERAL </th>

                                       <th colspan="" class="text-center"><?=$tot_g;?></th>
                                      
                                    </tr>

                                </tfoot>
                            </table>

                        </div>
                   
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
