<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/fiche_charge/add/<?php $this->uri->segment(4) ?>';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {

       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<style type="text/css">
  tr:hover td{
    background-color: #ccc !important;
  }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Fiche Prise en Charge<small></small>
   </h1>
   <h5 class="widget-user-desc"><i class="label bg-yellow"><?= $fiche_pc_count; ?> &nbsp; élément<?php if($fiche_pc_count > 1)echo 's'; ?></i></h5>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Accueil</a></li>
      <li class="active">Fiche PC</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <form name="form_fiche_pc" id="form_fiche_travail" action="<?= base_url('administrator/fiche_charge/index/'.$this->uri->segment(4)); ?>">
                        <div class="widget-user-header ">
                         <div class="row pull-center" style="margin-left:5%">
                          <div  class="col-md-8">
                             <div class="col-sm-4 padd-left-0  " >
                                <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                             </div>
                             <div class="col-sm-3 padd-left-0 " >
                                <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                                   <option value=""><?= cclang('all'); ?></option>
                                    <option <?= $this->input->get('f') == 'NUMERO_PRISE_CHARGE' ? 'selected' :''; ?> value="NUMERO_PRISE_CHARGE">Numero</option>
                                    <option <?= $this->input->get('f') == 'DATE_CREATION_PRISE_CHARGE' ? 'selected' : ''; ?> value="DATE_CREATION_PRISE_CHARGE">Date création</option>
                                  </select>
                             </div>
                             <div class="col-sm-1 padd-left-0 ">
                                <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="Rechercher">
                                <i class="fa fa-search"></i>
                                </button>
                             </div>
                             <div class="col-sm-1 padd-left-0 ">
                                <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/garage/index/'.$this->uri->segment(4));?>" title="<?= cclang('reset_filter'); ?>">
                                <i class="fa fa-undo"></i>
                                </a>
                             </div>
                          </div>
                            <?php is_allowed('maintenance_add', function(){?>
                            <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="" href="<?=  site_url('administrator/fiche_charge/add/'.$this->uri->segment(4)); ?>"><i class="fa fa-plus" ></i></a>
                            <a class="btn btn-flat btn-info" id="export_excel" title="export excel" href="" onclick="exportToExcel()"><i class="fa fa-file-excel-o" ></i> Export XLS</a>
                            <a class="btn btn-secondary" title="imprimer" href="" onclick="myFunction()"><i class="fa fa-print" ></i> Imprimer</a>
                            <?php }) ?>
                        </div>
                      </div>
                  </form>

                  <div class="table-responsive"> 
                    <table class="table table-bordered table-striped dataTable" id="fiche_charge_table">
                     <thead>
                        <tr>
                           <th>&#8470; &nbsp;</th>
                           <th>&#8470; &nbsp; FPC</th>
                           <th>Client</th>
                           <th>Par</th>
                           <th>Date de création</th>
                           <th>Statut</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_garage">
                     <?php $i = 0;
                     foreach($fiche_pc as $fiche_pc): 
                      $i++;
                      ?>
                        <tr>
                          <td><?= $i?></td>
                          <td><?= _ent($fiche_pc->NUMERO_PRISE_CHARGE); ?></td>
                          <td><?= _ent($fiche_pc->NOM_CLIENT); ?></td>
                          <td><?= _ent($fiche_pc->full_name); ?></td> 
                          <td><?= _ent($fiche_pc->DATE_CREATION_PRISE_CHARGE); ?></td>
                          <td><?php 
                              $num = _ent($fiche_pc->ID_PRISE_CHARGE);
                              $query_statut = $this->db->get_where('pos_store_'.$this->uri->segment(4).'_ibi_devis', array('REF_FICHE_PC'=>$num))->row();
                              $check = isset($query_statut->REF_FICHE_PC) ? 'Avec devis' : 'Sans devis';
                              echo $statut = isset($query_statut->REF_FICHE_PC) ? '<span class="btn btn-primary btn-xs">'.$check.'</span>' : '<span class="btn btn-warning btn-xs">'.$check.'</span>';
                           ?></td> 
                         <td width="150">
                          <?php is_allowed('maintenance_view', function() use ($fiche_pc){?>  
                            <a title="voir détail du fiche_pc" href="<?= site_url('administrator/fiche_charge/view/'.$this->uri->segment(4).'/' . $fiche_pc->ID_PRISE_CHARGE); ?>" class="btn btn-warning btn-xs"><i class="fa fa-eye "></i> </a>                
                            <!-- <a  title="Créer un proforma" class="btn btn-info btn-xs" data-toggle="modal" data-target="#myModal<?php echo $fiche_pc->ID_PRISE_CHARGE; ?>"><i class="fa fa-print"></i></a> -->
                          <?php });
                              if($check == 'Sans devis') {
                           ?>
                            <?php is_allowed('maintenance_update', function() use ($fiche_pc){?>
                              <a title="Modification du fiche_pc" href="<?= site_url('administrator/fiche_charge/edit/'.$this->uri->segment(4).'/' . $fiche_pc->ID_PRISE_CHARGE); ?>" class="btn btn-default btn-xs"><i class="fa fa-edit "></i> </a>
                              <?php }) ?>
                              <?php is_allowed('maintenance_delete', function() use ($fiche_pc){?>
                              <a title="Supprimer ce fiche_pc" href="javascript:void(0);" id="<?= $fiche_pc->ID_PRISE_CHARGE ?>" class="btn btn-danger btn-xs remove-data bt_delete"><i class="fa fa-close"></i></a>
                               <?php }) ?>
                               <?php is_allowed('maintenance_generate', function() use ($fiche_pc){?>
                              <a title="Générer le devis" href="<?= site_url('administrator/fiche_charge/generate/'.$this->uri->segment(4)).'/'.$fiche_pc->ID_PRISE_CHARGE; ?>" id="<?= $fiche_pc->ID_PRISE_CHARGE ?>" class="btn btn-info btn-xs remove-data bt_generate"><i class="fa fa-list-alt"></i></a>
                               <?php }); } ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      </tbody>
                    </table>
                  </div>
                </div>

                <hr>
                 <div class="row" id="pagination">
                    <div class="col-md-8">
                    </div>                
                    <div class="col-md-4">
                       <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                          <?= $pagination; ?>
                       </div>
                    </div>
                 </div>

                 </div>
            </div>
            <!--/box body -->
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->

<script type="text/javascript">
   $(document).ready(function() {
    $(document).on('click', '.bt_delete', function() {

      var id = $(this).attr('id');

      swal({

          title: "Êtes-vous sûr?",
          text: "La suppression sera définitive; pas moyen de revenir!",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Oui, Supprimer-le!",
          cancelButtonText: "Non, Annuler plx ",
          closeOnConfirm: true,
          closeOnCancel: true

        },
        function(isConfirm) {
          if (isConfirm) {
            // console.log(id);
            document.location.href = BASE_URL + 'administrator/fiche_charge/delete/<?=$this->uri->segment(4);?>/'+id;
          }
        }); //end swal

      return false;


    });
   })

   //export in excel
  function exportToExcel() {
       var tab_text = '<table charset="utf-8" border="1px" style="font-size:20px" ">';
       var textRange; 
       var j = 0;
       var tab = document.getElementById('fiche_charge_table'); // id of table
       var tab1 = tab;
       var lines = tab1.rows.length;

       // the first headline of the table
       if (lines > 0) {
         tab1.rows[0].deleteCell(8);
           tab_text = tab_text + '<tr bgcolor="#DFDFDF">' + tab1.rows[0].innerHTML + '</tr>';
       }

       // table data lines, loop starting from 1
       for (j = 1 ; j < lines; j++) { 
         tab1.rows[j].deleteCell(8);
           tab_text = tab_text + "<tr>" + tab1.rows[j].innerHTML + "</tr>";
       }
       // console.log(columns);
       tab_text = tab_text + "</table>";
       tab_text = tab_text.replace(/<A[^>]*>|<\/A>/g, "");             //remove if u want links in your table
       tab_text = tab_text.replace(/<img[^>]*>/gi,"");                 // remove if u want images in your table
       tab_text = tab_text.replace(/<input[^>]*>|<\/input>/gi, "");    // reomves input params
       // console.log(tab_text); // aktivate so see the result (press F12 in browser)

       var ua = window.navigator.userAgent;
       var msie = ua.indexOf("MSIE "); 

        // if Internet Explorer
       if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) {
           txtArea1.document.open("txt/html","replace");
           txtArea1.document.write(tab_text);
           txtArea1.document.close();
           txtArea1.focus(); 
           sa = txtArea1.document.execCommand("SaveAs", true, "DataTableExport.xls");
       }  
       else // other browser not tested on IE 11
           sa = window.open('data:application/vnd.ms-excel,' + escape(tab_text));  

       return (sa);
   }
    function myFunction()
    {
        window.print();
    }
</script>
<style type="text/css">
    @media print {
        @page{size: a4 landscape;}
        form, footer, td:nth-last-child(1), th:nth-last-child(1), hr, #pagination {
            display: none;
        }
    }
</style>