
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Détail du devis      <small> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Accueil</a></li>
      <li class=""><a  href="<?= site_url('administrator/devis/index/'.$this->uri->segment(4)); ?>">Devis</a></li>
      <li class="active">Détail</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Devis</h3>
                     <h5 class="widget-user-desc">Détail devis</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_pos_store_2_ibi_devis" id="form_pos_store_2_ibi_devis" >





                  <div class="table-responsive"> 

                  <table class="table table-bordered table-striped dataTable">
                     <thead>

                        <tr style="background-color: #ccc !important;">

                           <th class="cell" style="text-align: center; background-color: #ccc;border:1px solid black !important;">&#8470;</th>

                        <th class="cell" style="text-align: center;border:1px solid black !important;">&#8470;&nbsp;du produit </th>

                           <th class="cell" style="text-align: center;border:1px solid black !important;">Description</th>

                          

                          <th class="cell" style="text-align: center;border:1px solid black !important;">Quantité</th>

                           <th class="cell" style="text-align: center;border:1px solid black !important;">PU</th>

                           <th class="cell" style="text-align: center;border:1px solid black !important;">PT</th>
                         </tr>

                     </thead>

                     
                     <tbody> 

<?php
$prix_total_all=0;
$i=0;
 foreach ($devis as $data) { 
  $i++;

$prix_total=$data['QUANTITE_DEVIS_PROD']*$data['PRIX_DEVIS_PROD'];

$prix_total_all += $data['QUANTITE_DEVIS_PROD']*$data['PRIX_DEVIS_PROD'];

 $status=$data['STATUT_DEVIS'];

 $coefficient=$data['COEFFICIENT_DEVIS'];

 $total=$data['TOTAL_FINAL_DEVIS'];

  ?>


                     <tr >

                        <td style="text-align: center;border:1px solid black !important;"> <?php echo $i; ?></td>

                         <td style="text-align: center;border:1px solid black !important;"> <?php echo $data['REF_PRODUCT_CODEBAR_DEVIS_PROD']; ?></td>

                        <td style="text-align: center;border:1px solid black !important;"> <?php echo $data['NAME_DEVIS_PROD']; ?></td>

                          <td style="text-align: center;border:1px solid black !important;"><?php echo $data['QUANTITE_DEVIS_PROD']; ?> &nbsp; <?php echo $data['UNIT_DEVIS_PROD']; ?></td>

                        <td style="text-align: center;border:1px solid black !important;"><?php echo  number_format( $data['PRIX_DEVIS_PROD'],0," "," "); ?></td>
                       
                        <td style="text-align: center;border:1px solid black !important;"> <?php echo number_format($prix_total,0," "," "); ?></td>
  

                     </tr>
<?php } ?>

                    <tr>
                      <td colspan="4">
                      </td>
                      <td style="text-align: center;border-right: 1px solid black !important;"><b>Total</b></td>
                      <td style="text-align: center;border:1px solid black !important;border-left: 1px solid black !important;"><?php echo number_format($prix_total_all,0," "," "); ?></td>
                      
                    </tr>


                    <tr>
                      <td colspan="4">
                      </td>
                      <td style="text-align: right;border-right: 1px solid black !important;"><b>Coéfficient</b>
                        &nbsp; &nbsp; 
                        <a data-toggle="modal" title="Modification ce coéfficient" data-target="#myModal"class="btn btn-primary btn-xs"> <i class="fa fa-edit"></i>
                        </td>
                      <td style="text-align: right;border:1px solid black !important;border-left: 1px solid black !important;">
                          <?php echo $coefficient; ?> </a>


                      </td>
                      
                    </tr>
                   <?php $general_total = $coefficient * $prix_total_all;?>
                     <tr>
                      <td colspan="4">
                      </td>
                      <td style="text-align: right;border-right: 1px solid black !important;"><b>Total général</b></td>
                      <td style="text-align: right;border:1px solid black !important;border-left: 1px solid black !important;"><?php echo number_format($general_total,0," "," "); ?></td>
                      
                    </tr>
                

                    <tr>
                    <td colspan="4">
                    </td>
                      <td style="text-align: right;border-right: 1px solid black !important;"><b>Cout de production</b>
                        &nbsp; &nbsp; 
                        <a data-toggle="modal" title="Modifier ce cout de production" data-target="#myModals"class="btn btn-primary btn-xs"> <i class="fa fa-edit"></i> </a></td>
                     <td style="text-align: right;border:1px solid black !important;border-left: 1px solid black !important;"><?php

                       if($total==0){
                        echo number_format($general_total,0," "," ");
                      }else{
                        echo number_format($total,0," "," ");
                      }
                      


                       ?></td>
                      
                    </tr>







                   </tbody>

                  </table>
                  </div>





<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <div  style="background-color: #7FFFD4;" class="modal-header">
        <h4 class="modal-title">Modification du coéfficient</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>


            <?= form_open('', [

              'name'    => 'form_nurse_activity',

              'class'   => 'form-horizontal',

              'id'      => 'form_nurse_activity',

              'enctype' => 'multipart/form-data',

              'method'  => 'POST'

            ]); ?>



      <div class="modal-body">
        

              
<input type="hidden"  name="devis_id" value="<?php echo($this->uri->segment(4)); ?>">

                       <div class="form-group ">
                            <label for="TITRE_DEVIS" class="col-sm-3 control-label">Coéfficient 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control coefficient" name="coefficient_name" id="TITRE_DEVIS" placeholder="Entrer un coéfficient" value="">
                                <small class="info help-block">
                                </small>
                            </div>
                        </div>
           

         

      </div>




      <!-- Modal footer -->
       <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>
        <button  data-stype='back' class="btn btn-primary btn_save btn_action btn_save_back verifier">Envoyer</button>
      </div>

      <?= form_close(); ?>
    </div>
  </div>
</div>  




















                   <div class="view-nav">

                    <?php if($status==0){ ?>

                        <?php is_allowed('devis_update', function() use ($pos_store_2_ibi_devis){?>



                          <a class="btn btn-flat btn-primary btn_action" id="btn_cancel" title="<?= cclang('cancel_button'); ?> (Ctrl+x)">
                            <i class="fa fa-check" ></i><input type="hidden" id="devis_id" value="<?php echo $this->uri->segment(4); ?>" name="id_devis">&nbsp; Approuver
                            </a>





                         <!-- 
                        <a  class="btn btn-flat btn-primary btn_edit btn_action" id="btn_edit" data-stype='back' title="Approuver la commande" href="<?//= site_url('administrator/pos_store_2_ibi_devis/approuver_commande/'.$this->uri->segment(4)); ?>"><i class="fa fa-ok" ></i> Approuver </a> -->
                        <?php }); ?>


                      <?php } ?>


                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="Retourner à la page précédente" href="<?= site_url('administrator/devis/index/'.$this->uri->segment(4);); ?>"><i class="fa fa-undo" ></i> &nbsp;Retourner</a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->






<div class="modal fade" id="myModals">
  <div class="modal-dialog">
    <div class="modal-content">

      <div  style="background-color: #7FFFD4;" class="modal-header">
        <h4 class="modal-title">Modification du cout de production</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>


            <?= form_open('', [

              'name'    => 'form_nurse_activitys',

              'class'   => 'form-horizontals',

              'id'      => 'form_nurse_activitys',

              'enctype' => 'multipart/form-data',

              'method'  => 'POST'

            ]); ?>



      <div class="modal-body">
        

              
<input type="hidden"  name="devis_id" value="<?php echo($this->uri->segment(5)); ?>">

                       <div class="form-group ">
                            <label for="TITRE_DEVIS" class="col-sm-3 control-label">Cout production 
                            <i class="required">*</i>
                            </label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control production" name="production_name" id="TITRE_DEVIS" placeholder="Entrer un cout de production" value="">
                                <small class="info help-block">
                                </small>
                            </div>
                        </div>
           

         

      </div>




      <!-- Modal footer -->
       <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>
        <button  data-stype='back' class="btn btn-primary btn_save btn_action btn_save_back verifiers">Envoyer</button>
      </div>

      <?= form_close(); ?>
    </div>
  </div>
</div>  














<script>
  $(document).ready(function(){
   
       $('#btn_cancel').click(function(){
        var id_devis=$('#devis_id').val();
        //alert(id_devis);
        swal({
            title: "Êtes-vous sûr de vouloir Approuver",
            text: "Le devis deviendra une fiche de travail",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes!",
            cancelButtonText: "No!",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
              window.location.href = BASE_URL + 'administrator/pos_store_2_ibi_devis/approuver_commande/'+id_devis;
            }
          });
    
        return false;
      }); /*end btn cancel*/



$('.verifier').click(function(){


var coefficient = $(".coefficient").val();







if(coefficient ==''){
  sweetAlert('Donner un coéfficient avant d\'envoyer');
   return false;
}


else{
      
       //avoid_multi_click_btn('btn_save', 5000);


        var form_nurse_activity = $('#form_nurse_activity');

        var data_post = form_nurse_activity.serializeArray();

        var save_type = $(this).attr('data-stype');



        data_post.push({
          name: 'save_type',
          value: save_type
        });



        $('.loading').show();



        $.ajax({


            url: BASE_URL + '/administrator/pos_store_2_ibi_devis/coefficient',

            type: 'POST',

            dataType: 'json',

            data: data_post,

          })

          .done(function(res) {

            if (res.success) {



              if (save_type == 'back') {

                window.location.href = res.redirect;

                return;

              }



              $('.message').printMessage({
                message: res.message
              });

              $('.message').fadeIn();

              resetForm();

              $('.chosen option').prop('selected', false).trigger('chosen:updated');



            } else {

              $('.message').printMessage({
                message: res.message,
                type: 'warning'
              });

            }



          })

          .fail(function() {

            $('.message').printMessage({
              message: 'Error save data',
              type: 'warning'
            });

          })

          .always(function() {

            $('.loading').hide();

            $('html, body').animate({
              scrollTop: $(document).height()
            }, 2000);

          });




        return false;



         }


    });//end of edit coefficient












$('.verifiers').click(function(){


var production = $(".production").val();







if(production ==''){
  sweetAlert('Donner un cout de production avant d\'envoyer');
   return false;
}


else{
      
       //avoid_multi_click_btn('btn_save', 5000);


        var form_nurse_activity = $('#form_nurse_activitys');

        var data_post = form_nurse_activity.serializeArray();

        var save_type = $(this).attr('data-stype');



        data_post.push({
          name: 'save_type',
          value: save_type
        });



        $('.loading').show();



        $.ajax({


            url: BASE_URL + '/administrator/pos_store_2_ibi_devis/cout_production_update',

            type: 'POST',

            dataType: 'json',

            data: data_post,

          })

          .done(function(res) {

            if (res.success) {



              if (save_type == 'back') {

                window.location.href = res.redirect;

                return;

              }



              $('.message').printMessage({
                message: res.message
              });

              $('.message').fadeIn();

              resetForm();

              $('.chosen option').prop('selected', false).trigger('chosen:updated');



            } else {

              $('.message').printMessage({
                message: res.message,
                type: 'warning'
              });

            }



          })

          .fail(function() {

            $('.message').printMessage({
              message: 'Error save data',
              type: 'warning'
            });

          })

          .always(function() {

            $('.loading').hide();

            $('html, body').animate({
              scrollTop: $(document).height()
            }, 2000);

          });




        return false;



         }


    });//end of edit coefficient





     }); /*end doc ready*/
</script>