
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Pos Store 2 Ibi Client File      <small><?= cclang('detail', ['Pos Store 2 Ibi Client File']); ?> </small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/pos_store_2_ibi_client_file'); ?>">Pos Store 2 Ibi Client File</a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Pos Store 2 Ibi Client File</h3>
                     <h5 class="widget-user-desc">Detail Pos Store 2 Ibi Client File</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_pos_store_2_ibi_client_file" id="form_pos_store_2_ibi_client_file" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ID CLIENT FILE </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->ID_CLIENT_FILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PROFORMA ID CLIENT FILE </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->PROFORMA_ID_CLIENT_FILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">REF CLIENT FILE </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->REF_CLIENT_FILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">REF PROFORMA CODE CLIENT FILE </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->REF_PROFORMA_CODE_CLIENT_FILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">NUMBER PURCHASE CLIENT FILE </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->NUMBER_PURCHASE_CLIENT_FILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> FILE PURCHASE CLIENT FILE </label>
                        <div class="col-sm-8">
                             <?php if (is_image($pos_store_2_ibi_client_file->FILE_PURCHASE_CLIENT_FILE)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->FILE_PURCHASE_CLIENT_FILE; ?>">
                                <img src="<?= BASE_URL . 'uploads/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->FILE_PURCHASE_CLIENT_FILE; ?>" class="image-responsive" alt="image pos_store_2_ibi_client_file" title="FILE_PURCHASE_CLIENT_FILE pos_store_2_ibi_client_file" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->FILE_PURCHASE_CLIENT_FILE; ?>">
                                 <img src="<?= get_icon_file($pos_store_2_ibi_client_file->FILE_PURCHASE_CLIENT_FILE); ?>" class="image-responsive" alt="image pos_store_2_ibi_client_file" title="FILE_PURCHASE_CLIENT_FILE <?= $pos_store_2_ibi_client_file->FILE_PURCHASE_CLIENT_FILE; ?>" width="40px"> 
                               <?= $pos_store_2_ibi_client_file->FILE_PURCHASE_CLIENT_FILE ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> COMMISSIONING CLIENT FILE </label>
                        <div class="col-sm-8">
                             <?php if (is_image($pos_store_2_ibi_client_file->COMMISSIONING_CLIENT_FILE)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->COMMISSIONING_CLIENT_FILE; ?>">
                                <img src="<?= BASE_URL . 'uploads/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->COMMISSIONING_CLIENT_FILE; ?>" class="image-responsive" alt="image pos_store_2_ibi_client_file" title="COMMISSIONING_CLIENT_FILE pos_store_2_ibi_client_file" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->COMMISSIONING_CLIENT_FILE; ?>">
                                 <img src="<?= get_icon_file($pos_store_2_ibi_client_file->COMMISSIONING_CLIENT_FILE); ?>" class="image-responsive" alt="image pos_store_2_ibi_client_file" title="COMMISSIONING_CLIENT_FILE <?= $pos_store_2_ibi_client_file->COMMISSIONING_CLIENT_FILE; ?>" width="40px"> 
                               <?= $pos_store_2_ibi_client_file->COMMISSIONING_CLIENT_FILE ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> CONTRAT GARANTIE CLIENT FILE </label>
                        <div class="col-sm-8">
                             <?php if (is_image($pos_store_2_ibi_client_file->CONTRAT_GARANTIE_CLIENT_FILE)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->CONTRAT_GARANTIE_CLIENT_FILE; ?>">
                                <img src="<?= BASE_URL . 'uploads/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->CONTRAT_GARANTIE_CLIENT_FILE; ?>" class="image-responsive" alt="image pos_store_2_ibi_client_file" title="CONTRAT_GARANTIE_CLIENT_FILE pos_store_2_ibi_client_file" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->CONTRAT_GARANTIE_CLIENT_FILE; ?>">
                                 <img src="<?= get_icon_file($pos_store_2_ibi_client_file->CONTRAT_GARANTIE_CLIENT_FILE); ?>" class="image-responsive" alt="image pos_store_2_ibi_client_file" title="CONTRAT_GARANTIE_CLIENT_FILE <?= $pos_store_2_ibi_client_file->CONTRAT_GARANTIE_CLIENT_FILE; ?>" width="40px"> 
                               <?= $pos_store_2_ibi_client_file->CONTRAT_GARANTIE_CLIENT_FILE ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label"> CONTRAT MAINTENANCE CLIENT FILE </label>
                        <div class="col-sm-8">
                             <?php if (is_image($pos_store_2_ibi_client_file->CONTRAT_MAINTENANCE_CLIENT_FILE)): ?>
                              <a class="fancybox" rel="group" href="<?= BASE_URL . 'uploads/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->CONTRAT_MAINTENANCE_CLIENT_FILE; ?>">
                                <img src="<?= BASE_URL . 'uploads/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->CONTRAT_MAINTENANCE_CLIENT_FILE; ?>" class="image-responsive" alt="image pos_store_2_ibi_client_file" title="CONTRAT_MAINTENANCE_CLIENT_FILE pos_store_2_ibi_client_file" width="40px">
                              </a>
                              <?php else: ?>
                              <label>
                                <a href="<?= BASE_URL . 'administrator/file/download/pos_store_2_ibi_client_file/' . $pos_store_2_ibi_client_file->CONTRAT_MAINTENANCE_CLIENT_FILE; ?>">
                                 <img src="<?= get_icon_file($pos_store_2_ibi_client_file->CONTRAT_MAINTENANCE_CLIENT_FILE); ?>" class="image-responsive" alt="image pos_store_2_ibi_client_file" title="CONTRAT_MAINTENANCE_CLIENT_FILE <?= $pos_store_2_ibi_client_file->CONTRAT_MAINTENANCE_CLIENT_FILE; ?>" width="40px"> 
                               <?= $pos_store_2_ibi_client_file->CONTRAT_MAINTENANCE_CLIENT_FILE ?>
                               </a>
                               </label>
                              <?php endif; ?>
                        </div>
                    </div>
                                       
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">INVOICE NUMBER CLIENT FILE </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->INVOICE_NUMBER_CLIENT_FILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DATE CREATION CLIENT FILE </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->DATE_CREATION_CLIENT_FILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DATE MODIFICATION CLIENT FILE </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->DATE_MODIFICATION_CLIENT_FILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">OPERATING STATUT </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->OPERATING_STATUT); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">APPROUVE BY </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->APPROUVE_BY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CLOSURE DATE CLIENT FILE </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->CLOSURE_DATE_CLIENT_FILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CLOSURE BY CLIENT FILE </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->CLOSURE_BY_CLIENT_FILE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">AUTHOR </label>

                        <div class="col-sm-8">
                           <?= _ent($pos_store_2_ibi_client_file->AUTHOR); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('pos_store_2_ibi_client_file_update', function() use ($pos_store_2_ibi_client_file){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit pos_store_2_ibi_client_file (Ctrl+e)" href="<?= site_url('administrator/pos_store_2_ibi_client_file/edit/'.$pos_store_2_ibi_client_file->ID_CLIENT_FILE); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', ['Pos Store 2 Ibi Client File']); ?> </a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/pos_store_2_ibi_client_file/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list_button', ['Pos Store 2 Ibi Client File']); ?></a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
